/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fifo_sync(clk, rst_n, wr_en, wr_data, full, almost_full, overflow, rd_en, rd_data, empty, almost_empty, underflow, data_count, peak_count);
  wire [31:0] _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  output almost_empty;
  reg almost_empty;
  output almost_full;
  reg almost_full;
  input clk;
  wire clk;
  output [4:0] data_count;
  reg [4:0] data_count;
  output empty;
  reg empty;
  output full;
  reg full;
  reg [31:0] \mem[0] ;
  reg [31:0] \mem[10] ;
  reg [31:0] \mem[11] ;
  reg [31:0] \mem[12] ;
  reg [31:0] \mem[13] ;
  reg [31:0] \mem[14] ;
  reg [31:0] \mem[15] ;
  reg [31:0] \mem[1] ;
  reg [31:0] \mem[2] ;
  reg [31:0] \mem[3] ;
  reg [31:0] \mem[4] ;
  reg [31:0] \mem[5] ;
  reg [31:0] \mem[6] ;
  reg [31:0] \mem[7] ;
  reg [31:0] \mem[8] ;
  reg [31:0] \mem[9] ;
  wire [4:0] next_data_count;
  wire [4:0] next_rd_ptr;
  wire [4:0] next_wr_ptr;
  output overflow;
  reg overflow;
  output [4:0] peak_count;
  reg [4:0] peak_count;
  wire [3:0] rd_addr;
  output [31:0] rd_data;
  reg [31:0] rd_data;
  input rd_en;
  wire rd_en;
  reg [4:0] rd_ptr;
  input rst_n;
  wire rst_n;
  output underflow;
  reg underflow;
  wire [3:0] wr_addr;
  input [31:0] wr_data;
  wire [31:0] wr_data;
  input wr_en;
  wire wr_en;
  reg [4:0] wr_ptr;
  assign _0229_ = full | ~(wr_en);
  assign _0230_ = _0229_ ^ wr_ptr[0];
  assign _0231_ = empty | ~(rd_en);
  assign _0232_ = _0231_ ^ rd_ptr[0];
  assign next_data_count[0] = _0232_ ^ _0230_;
  assign _0233_ = wr_ptr[1] ^ wr_ptr[0];
  assign next_wr_ptr[1] = _0229_ ? wr_ptr[1] : _0233_;
  assign _0234_ = ~rd_ptr[1];
  assign _0235_ = ~(rd_ptr[1] ^ rd_ptr[0]);
  assign _0236_ = _0231_ ? _0234_ : _0235_;
  assign _0237_ = _0236_ ^ next_wr_ptr[1];
  assign _0238_ = _0230_ & ~(_0232_);
  assign _0239_ = _0238_ ^ _0237_;
  assign _0240_ = _0239_ | next_data_count[0];
  assign _0241_ = ~wr_ptr[3];
  assign _0242_ = ~wr_ptr[2];
  assign _0243_ = wr_ptr[1] & wr_ptr[0];
  assign _0244_ = _0243_ & ~(_0242_);
  assign _0245_ = _0244_ ^ _0241_;
  assign _0246_ = _0229_ ? _0241_ : _0245_;
  assign _0247_ = ~rd_ptr[3];
  assign _0248_ = ~rd_ptr[2];
  assign _0249_ = rd_ptr[1] & rd_ptr[0];
  assign _0250_ = _0249_ & ~(_0248_);
  assign _0251_ = _0250_ ^ _0247_;
  assign _0252_ = _0231_ ? _0247_ : _0251_;
  assign _0253_ = _0252_ ^ _0246_;
  assign _0254_ = ~_0253_;
  assign _0255_ = _0243_ ^ wr_ptr[2];
  assign next_wr_ptr[2] = _0229_ ? wr_ptr[2] : _0255_;
  assign _0256_ = _0249_ ^ _0248_;
  assign _0257_ = _0231_ ? _0248_ : _0256_;
  assign _0258_ = ~(_0257_ & next_wr_ptr[2]);
  assign _0259_ = _0257_ ^ next_wr_ptr[2];
  assign _0260_ = ~(_0236_ & next_wr_ptr[1]);
  assign _0261_ = _0237_ & ~(_0238_);
  assign _0262_ = _0260_ & ~(_0261_);
  assign _0263_ = _0259_ & ~(_0262_);
  assign _0264_ = _0258_ & ~(_0263_);
  assign _0265_ = _0264_ ^ _0254_;
  assign _0266_ = _0262_ ^ _0259_;
  assign next_data_count[2] = ~_0266_;
  assign _0267_ = next_data_count[2] & ~(_0265_);
  assign _0268_ = _0267_ & ~(_0240_);
  assign _0269_ = ~wr_ptr[4];
  assign _0270_ = ~(wr_ptr[3] & wr_ptr[2]);
  assign _0271_ = _0243_ & ~(_0270_);
  assign _0272_ = _0271_ ^ _0269_;
  assign _0273_ = _0229_ ? _0269_ : _0272_;
  assign _0274_ = ~rd_ptr[4];
  assign _0275_ = ~(rd_ptr[2] & rd_ptr[3]);
  assign _0276_ = _0249_ & ~(_0275_);
  assign _0277_ = _0276_ ^ _0274_;
  assign _0278_ = _0231_ ? _0274_ : _0277_;
  assign _0279_ = _0278_ ^ _0273_;
  assign _0280_ = _0246_ | ~(_0252_);
  assign _0281_ = ~(_0258_ | _0253_);
  assign _0282_ = _0280_ & ~(_0281_);
  assign _0283_ = _0253_ | ~(_0259_);
  assign _0284_ = ~(_0283_ | _0262_);
  assign _0285_ = _0282_ & ~(_0284_);
  assign _0286_ = ~(_0285_ ^ _0279_);
  assign next_data_count[4] = ~_0286_;
  assign _0287_ = _0268_ & ~(next_data_count[4]);
  assign _0288_ = next_data_count[0] & ~(_0239_);
  assign _0289_ = _0267_ & ~(_0288_);
  assign _0290_ = _0267_ & ~(_0289_);
  assign _0291_ = _0290_ | next_data_count[4];
  assign _0002_ = _0291_ | _0287_;
  assign _0292_ = ~(_0266_ & _0265_);
  assign _0293_ = _0292_ | _0240_;
  assign _0294_ = _0286_ & ~(_0293_);
  assign _0295_ = _0292_ | _0288_;
  assign _0296_ = _0286_ & ~(_0295_);
  assign _0001_ = _0296_ | _0294_;
  assign _0297_ = ~(_0232_ ^ _0230_);
  assign _0298_ = ~(_0236_ ^ next_wr_ptr[1]);
  assign _0299_ = _0297_ & ~(_0298_);
  assign _0300_ = ~(_0257_ ^ next_wr_ptr[2]);
  assign _0301_ = _0253_ | _0300_;
  assign _0302_ = _0299_ & ~(_0301_);
  assign _0303_ = ~(_0278_ ^ _0273_);
  assign _0004_ = _0303_ & _0302_;
  assign _0006_ = wr_en & full;
  assign _0007_ = rd_en & empty;
  assign _0005_ = _0302_ & ~(_0303_);
  assign _0304_ = rd_ptr[0] ? \mem[1] [1] : \mem[0] [1];
  assign _0305_ = rd_ptr[0] ? \mem[3] [1] : \mem[2] [1];
  assign _0306_ = rd_ptr[1] ? _0305_ : _0304_;
  assign _0307_ = rd_ptr[0] ? \mem[5] [1] : \mem[4] [1];
  assign _0308_ = rd_ptr[0] ? \mem[7] [1] : \mem[6] [1];
  assign _0309_ = rd_ptr[1] ? _0308_ : _0307_;
  assign _0310_ = rd_ptr[2] ? _0309_ : _0306_;
  assign _0311_ = rd_ptr[0] ? \mem[9] [1] : \mem[8] [1];
  assign _0312_ = rd_ptr[0] ? \mem[11] [1] : \mem[10] [1];
  assign _0313_ = rd_ptr[1] ? _0312_ : _0311_;
  assign _0314_ = rd_ptr[0] ? \mem[13] [1] : \mem[12] [1];
  assign _0315_ = rd_ptr[0] ? \mem[15] [1] : \mem[14] [1];
  assign _0316_ = rd_ptr[1] ? _0315_ : _0314_;
  assign _0317_ = rd_ptr[2] ? _0316_ : _0313_;
  assign _0000_[1] = rd_ptr[3] ? _0317_ : _0310_;
  assign _0318_ = rd_ptr[0] ? \mem[1] [2] : \mem[0] [2];
  assign _0319_ = rd_ptr[0] ? \mem[3] [2] : \mem[2] [2];
  assign _0320_ = rd_ptr[1] ? _0319_ : _0318_;
  assign _0321_ = rd_ptr[0] ? \mem[5] [2] : \mem[4] [2];
  assign _0322_ = rd_ptr[0] ? \mem[7] [2] : \mem[6] [2];
  assign _0323_ = rd_ptr[1] ? _0322_ : _0321_;
  assign _0324_ = rd_ptr[2] ? _0323_ : _0320_;
  assign _0325_ = rd_ptr[0] ? \mem[9] [2] : \mem[8] [2];
  assign _0326_ = rd_ptr[0] ? \mem[11] [2] : \mem[10] [2];
  assign _0327_ = rd_ptr[1] ? _0326_ : _0325_;
  assign _0328_ = rd_ptr[0] ? \mem[13] [2] : \mem[12] [2];
  assign _0329_ = rd_ptr[0] ? \mem[15] [2] : \mem[14] [2];
  assign _0330_ = rd_ptr[1] ? _0329_ : _0328_;
  assign _0331_ = rd_ptr[2] ? _0330_ : _0327_;
  assign _0000_[2] = rd_ptr[3] ? _0331_ : _0324_;
  assign _0332_ = rd_ptr[0] ? \mem[1] [3] : \mem[0] [3];
  assign _0333_ = rd_ptr[0] ? \mem[3] [3] : \mem[2] [3];
  assign _0334_ = rd_ptr[1] ? _0333_ : _0332_;
  assign _0335_ = rd_ptr[0] ? \mem[5] [3] : \mem[4] [3];
  assign _0336_ = rd_ptr[0] ? \mem[7] [3] : \mem[6] [3];
  assign _0337_ = rd_ptr[1] ? _0336_ : _0335_;
  assign _0338_ = rd_ptr[2] ? _0337_ : _0334_;
  assign _0339_ = rd_ptr[0] ? \mem[9] [3] : \mem[8] [3];
  assign _0340_ = rd_ptr[0] ? \mem[11] [3] : \mem[10] [3];
  assign _0341_ = rd_ptr[1] ? _0340_ : _0339_;
  assign _0342_ = rd_ptr[0] ? \mem[13] [3] : \mem[12] [3];
  assign _0343_ = rd_ptr[0] ? \mem[15] [3] : \mem[14] [3];
  assign _0344_ = rd_ptr[1] ? _0343_ : _0342_;
  assign _0345_ = rd_ptr[2] ? _0344_ : _0341_;
  assign _0000_[3] = rd_ptr[3] ? _0345_ : _0338_;
  assign _0346_ = rd_ptr[0] ? \mem[1] [4] : \mem[0] [4];
  assign _0347_ = rd_ptr[0] ? \mem[3] [4] : \mem[2] [4];
  assign _0348_ = rd_ptr[1] ? _0347_ : _0346_;
  assign _0349_ = rd_ptr[0] ? \mem[5] [4] : \mem[4] [4];
  assign _0350_ = rd_ptr[0] ? \mem[7] [4] : \mem[6] [4];
  assign _0351_ = rd_ptr[1] ? _0350_ : _0349_;
  assign _0352_ = rd_ptr[2] ? _0351_ : _0348_;
  assign _0353_ = rd_ptr[0] ? \mem[9] [4] : \mem[8] [4];
  assign _0354_ = rd_ptr[0] ? \mem[11] [4] : \mem[10] [4];
  assign _0355_ = rd_ptr[1] ? _0354_ : _0353_;
  assign _0356_ = rd_ptr[0] ? \mem[13] [4] : \mem[12] [4];
  assign _0357_ = rd_ptr[0] ? \mem[15] [4] : \mem[14] [4];
  assign _0358_ = rd_ptr[1] ? _0357_ : _0356_;
  assign _0359_ = rd_ptr[2] ? _0358_ : _0355_;
  assign _0000_[4] = rd_ptr[3] ? _0359_ : _0352_;
  assign _0360_ = rd_ptr[0] ? \mem[1] [5] : \mem[0] [5];
  assign _0361_ = rd_ptr[0] ? \mem[3] [5] : \mem[2] [5];
  assign _0362_ = rd_ptr[1] ? _0361_ : _0360_;
  assign _0363_ = rd_ptr[0] ? \mem[5] [5] : \mem[4] [5];
  assign _0364_ = rd_ptr[0] ? \mem[7] [5] : \mem[6] [5];
  assign _0365_ = rd_ptr[1] ? _0364_ : _0363_;
  assign _0366_ = rd_ptr[2] ? _0365_ : _0362_;
  assign _0367_ = rd_ptr[0] ? \mem[9] [5] : \mem[8] [5];
  assign _0368_ = rd_ptr[0] ? \mem[11] [5] : \mem[10] [5];
  assign _0369_ = rd_ptr[1] ? _0368_ : _0367_;
  assign _0370_ = rd_ptr[0] ? \mem[13] [5] : \mem[12] [5];
  assign _0371_ = rd_ptr[0] ? \mem[15] [5] : \mem[14] [5];
  assign _0372_ = rd_ptr[1] ? _0371_ : _0370_;
  assign _0373_ = rd_ptr[2] ? _0372_ : _0369_;
  assign _0000_[5] = rd_ptr[3] ? _0373_ : _0366_;
  assign _0374_ = rd_ptr[0] ? \mem[1] [6] : \mem[0] [6];
  assign _0375_ = rd_ptr[0] ? \mem[3] [6] : \mem[2] [6];
  assign _0376_ = rd_ptr[1] ? _0375_ : _0374_;
  assign _0377_ = rd_ptr[0] ? \mem[5] [6] : \mem[4] [6];
  assign _0378_ = rd_ptr[0] ? \mem[7] [6] : \mem[6] [6];
  assign _0379_ = rd_ptr[1] ? _0378_ : _0377_;
  assign _0380_ = rd_ptr[2] ? _0379_ : _0376_;
  assign _0381_ = rd_ptr[0] ? \mem[9] [6] : \mem[8] [6];
  assign _0382_ = rd_ptr[0] ? \mem[11] [6] : \mem[10] [6];
  assign _0383_ = rd_ptr[1] ? _0382_ : _0381_;
  assign _0384_ = rd_ptr[0] ? \mem[13] [6] : \mem[12] [6];
  assign _0385_ = rd_ptr[0] ? \mem[15] [6] : \mem[14] [6];
  assign _0386_ = rd_ptr[1] ? _0385_ : _0384_;
  assign _0387_ = rd_ptr[2] ? _0386_ : _0383_;
  assign _0000_[6] = rd_ptr[3] ? _0387_ : _0380_;
  assign _0388_ = rd_ptr[0] ? \mem[1] [7] : \mem[0] [7];
  assign _0389_ = rd_ptr[0] ? \mem[3] [7] : \mem[2] [7];
  assign _0390_ = rd_ptr[1] ? _0389_ : _0388_;
  assign _0391_ = rd_ptr[0] ? \mem[5] [7] : \mem[4] [7];
  assign _0392_ = rd_ptr[0] ? \mem[7] [7] : \mem[6] [7];
  assign _0393_ = rd_ptr[1] ? _0392_ : _0391_;
  assign _0394_ = rd_ptr[2] ? _0393_ : _0390_;
  assign _0395_ = rd_ptr[0] ? \mem[9] [7] : \mem[8] [7];
  assign _0396_ = rd_ptr[0] ? \mem[11] [7] : \mem[10] [7];
  assign _0397_ = rd_ptr[1] ? _0396_ : _0395_;
  assign _0398_ = rd_ptr[0] ? \mem[13] [7] : \mem[12] [7];
  assign _0399_ = rd_ptr[0] ? \mem[15] [7] : \mem[14] [7];
  assign _0400_ = rd_ptr[1] ? _0399_ : _0398_;
  assign _0401_ = rd_ptr[2] ? _0400_ : _0397_;
  assign _0000_[7] = rd_ptr[3] ? _0401_ : _0394_;
  assign _0402_ = rd_ptr[0] ? \mem[1] [8] : \mem[0] [8];
  assign _0403_ = rd_ptr[0] ? \mem[3] [8] : \mem[2] [8];
  assign _0404_ = rd_ptr[1] ? _0403_ : _0402_;
  assign _0405_ = rd_ptr[0] ? \mem[5] [8] : \mem[4] [8];
  assign _0406_ = rd_ptr[0] ? \mem[7] [8] : \mem[6] [8];
  assign _0407_ = rd_ptr[1] ? _0406_ : _0405_;
  assign _0408_ = rd_ptr[2] ? _0407_ : _0404_;
  assign _0409_ = rd_ptr[0] ? \mem[9] [8] : \mem[8] [8];
  assign _0410_ = rd_ptr[0] ? \mem[11] [8] : \mem[10] [8];
  assign _0411_ = rd_ptr[1] ? _0410_ : _0409_;
  assign _0412_ = rd_ptr[0] ? \mem[13] [8] : \mem[12] [8];
  assign _0413_ = rd_ptr[0] ? \mem[15] [8] : \mem[14] [8];
  assign _0414_ = rd_ptr[1] ? _0413_ : _0412_;
  assign _0415_ = rd_ptr[2] ? _0414_ : _0411_;
  assign _0000_[8] = rd_ptr[3] ? _0415_ : _0408_;
  assign _0416_ = rd_ptr[0] ? \mem[1] [9] : \mem[0] [9];
  assign _0417_ = rd_ptr[0] ? \mem[3] [9] : \mem[2] [9];
  assign _0418_ = rd_ptr[1] ? _0417_ : _0416_;
  assign _0419_ = rd_ptr[0] ? \mem[5] [9] : \mem[4] [9];
  assign _0420_ = rd_ptr[0] ? \mem[7] [9] : \mem[6] [9];
  assign _0421_ = rd_ptr[1] ? _0420_ : _0419_;
  assign _0422_ = rd_ptr[2] ? _0421_ : _0418_;
  assign _0423_ = rd_ptr[0] ? \mem[9] [9] : \mem[8] [9];
  assign _0424_ = rd_ptr[0] ? \mem[11] [9] : \mem[10] [9];
  assign _0425_ = rd_ptr[1] ? _0424_ : _0423_;
  assign _0426_ = rd_ptr[0] ? \mem[13] [9] : \mem[12] [9];
  assign _0427_ = rd_ptr[0] ? \mem[15] [9] : \mem[14] [9];
  assign _0428_ = rd_ptr[1] ? _0427_ : _0426_;
  assign _0429_ = rd_ptr[2] ? _0428_ : _0425_;
  assign _0000_[9] = rd_ptr[3] ? _0429_ : _0422_;
  assign _0430_ = rd_ptr[0] ? \mem[1] [10] : \mem[0] [10];
  assign _0431_ = rd_ptr[0] ? \mem[3] [10] : \mem[2] [10];
  assign _0432_ = rd_ptr[1] ? _0431_ : _0430_;
  assign _0433_ = rd_ptr[0] ? \mem[5] [10] : \mem[4] [10];
  assign _0434_ = rd_ptr[0] ? \mem[7] [10] : \mem[6] [10];
  assign _0435_ = rd_ptr[1] ? _0434_ : _0433_;
  assign _0436_ = rd_ptr[2] ? _0435_ : _0432_;
  assign _0437_ = rd_ptr[0] ? \mem[9] [10] : \mem[8] [10];
  assign _0438_ = rd_ptr[0] ? \mem[11] [10] : \mem[10] [10];
  assign _0439_ = rd_ptr[1] ? _0438_ : _0437_;
  assign _0440_ = rd_ptr[0] ? \mem[13] [10] : \mem[12] [10];
  assign _0441_ = rd_ptr[0] ? \mem[15] [10] : \mem[14] [10];
  assign _0442_ = rd_ptr[1] ? _0441_ : _0440_;
  assign _0443_ = rd_ptr[2] ? _0442_ : _0439_;
  assign _0000_[10] = rd_ptr[3] ? _0443_ : _0436_;
  assign _0444_ = rd_ptr[0] ? \mem[1] [11] : \mem[0] [11];
  assign _0445_ = rd_ptr[0] ? \mem[3] [11] : \mem[2] [11];
  assign _0446_ = rd_ptr[1] ? _0445_ : _0444_;
  assign _0447_ = rd_ptr[0] ? \mem[5] [11] : \mem[4] [11];
  assign _0448_ = rd_ptr[0] ? \mem[7] [11] : \mem[6] [11];
  assign _0449_ = rd_ptr[1] ? _0448_ : _0447_;
  assign _0450_ = rd_ptr[2] ? _0449_ : _0446_;
  assign _0451_ = rd_ptr[0] ? \mem[9] [11] : \mem[8] [11];
  assign _0452_ = rd_ptr[0] ? \mem[11] [11] : \mem[10] [11];
  assign _0453_ = rd_ptr[1] ? _0452_ : _0451_;
  assign _0454_ = rd_ptr[0] ? \mem[13] [11] : \mem[12] [11];
  assign _0455_ = rd_ptr[0] ? \mem[15] [11] : \mem[14] [11];
  assign _0456_ = rd_ptr[1] ? _0455_ : _0454_;
  assign _0457_ = rd_ptr[2] ? _0456_ : _0453_;
  assign _0000_[11] = rd_ptr[3] ? _0457_ : _0450_;
  assign _0458_ = rd_ptr[0] ? \mem[1] [12] : \mem[0] [12];
  assign _0459_ = rd_ptr[0] ? \mem[3] [12] : \mem[2] [12];
  assign _0460_ = rd_ptr[1] ? _0459_ : _0458_;
  assign _0461_ = rd_ptr[0] ? \mem[5] [12] : \mem[4] [12];
  assign _0462_ = rd_ptr[0] ? \mem[7] [12] : \mem[6] [12];
  assign _0463_ = rd_ptr[1] ? _0462_ : _0461_;
  assign _0464_ = rd_ptr[2] ? _0463_ : _0460_;
  assign _0465_ = rd_ptr[0] ? \mem[9] [12] : \mem[8] [12];
  assign _0466_ = rd_ptr[0] ? \mem[11] [12] : \mem[10] [12];
  assign _0467_ = rd_ptr[1] ? _0466_ : _0465_;
  assign _0468_ = rd_ptr[0] ? \mem[13] [12] : \mem[12] [12];
  assign _0469_ = rd_ptr[0] ? \mem[15] [12] : \mem[14] [12];
  assign _0470_ = rd_ptr[1] ? _0469_ : _0468_;
  assign _0471_ = rd_ptr[2] ? _0470_ : _0467_;
  assign _0000_[12] = rd_ptr[3] ? _0471_ : _0464_;
  assign _0472_ = rd_ptr[0] ? \mem[1] [13] : \mem[0] [13];
  assign _0473_ = rd_ptr[0] ? \mem[3] [13] : \mem[2] [13];
  assign _0474_ = rd_ptr[1] ? _0473_ : _0472_;
  assign _0475_ = rd_ptr[0] ? \mem[5] [13] : \mem[4] [13];
  assign _0476_ = rd_ptr[0] ? \mem[7] [13] : \mem[6] [13];
  assign _0477_ = rd_ptr[1] ? _0476_ : _0475_;
  assign _0478_ = rd_ptr[2] ? _0477_ : _0474_;
  assign _0479_ = rd_ptr[0] ? \mem[9] [13] : \mem[8] [13];
  assign _0480_ = rd_ptr[0] ? \mem[11] [13] : \mem[10] [13];
  assign _0481_ = rd_ptr[1] ? _0480_ : _0479_;
  assign _0482_ = rd_ptr[0] ? \mem[13] [13] : \mem[12] [13];
  assign _0483_ = rd_ptr[0] ? \mem[15] [13] : \mem[14] [13];
  assign _0484_ = rd_ptr[1] ? _0483_ : _0482_;
  assign _0485_ = rd_ptr[2] ? _0484_ : _0481_;
  assign _0000_[13] = rd_ptr[3] ? _0485_ : _0478_;
  assign _0486_ = rd_ptr[0] ? \mem[1] [14] : \mem[0] [14];
  assign _0487_ = rd_ptr[0] ? \mem[3] [14] : \mem[2] [14];
  assign _0488_ = rd_ptr[1] ? _0487_ : _0486_;
  assign _0489_ = rd_ptr[0] ? \mem[5] [14] : \mem[4] [14];
  assign _0490_ = rd_ptr[0] ? \mem[7] [14] : \mem[6] [14];
  assign _0491_ = rd_ptr[1] ? _0490_ : _0489_;
  assign _0492_ = rd_ptr[2] ? _0491_ : _0488_;
  assign _0493_ = rd_ptr[0] ? \mem[9] [14] : \mem[8] [14];
  assign _0494_ = rd_ptr[0] ? \mem[11] [14] : \mem[10] [14];
  assign _0495_ = rd_ptr[1] ? _0494_ : _0493_;
  assign _0496_ = rd_ptr[0] ? \mem[13] [14] : \mem[12] [14];
  assign _0497_ = rd_ptr[0] ? \mem[15] [14] : \mem[14] [14];
  assign _0498_ = rd_ptr[1] ? _0497_ : _0496_;
  assign _0499_ = rd_ptr[2] ? _0498_ : _0495_;
  assign _0000_[14] = rd_ptr[3] ? _0499_ : _0492_;
  assign _0500_ = rd_ptr[0] ? \mem[1] [15] : \mem[0] [15];
  assign _0501_ = rd_ptr[0] ? \mem[3] [15] : \mem[2] [15];
  assign _0502_ = rd_ptr[1] ? _0501_ : _0500_;
  assign _0503_ = rd_ptr[0] ? \mem[5] [15] : \mem[4] [15];
  assign _0504_ = rd_ptr[0] ? \mem[7] [15] : \mem[6] [15];
  assign _0505_ = rd_ptr[1] ? _0504_ : _0503_;
  assign _0506_ = rd_ptr[2] ? _0505_ : _0502_;
  assign _0507_ = rd_ptr[0] ? \mem[9] [15] : \mem[8] [15];
  assign _0508_ = rd_ptr[0] ? \mem[11] [15] : \mem[10] [15];
  assign _0509_ = rd_ptr[1] ? _0508_ : _0507_;
  assign _0510_ = rd_ptr[0] ? \mem[13] [15] : \mem[12] [15];
  assign _0511_ = rd_ptr[0] ? \mem[15] [15] : \mem[14] [15];
  assign _0512_ = rd_ptr[1] ? _0511_ : _0510_;
  assign _0513_ = rd_ptr[2] ? _0512_ : _0509_;
  assign _0000_[15] = rd_ptr[3] ? _0513_ : _0506_;
  assign _0514_ = rd_ptr[0] ? \mem[1] [16] : \mem[0] [16];
  assign _0515_ = rd_ptr[0] ? \mem[3] [16] : \mem[2] [16];
  assign _0516_ = rd_ptr[1] ? _0515_ : _0514_;
  assign _0517_ = rd_ptr[0] ? \mem[5] [16] : \mem[4] [16];
  assign _0518_ = rd_ptr[0] ? \mem[7] [16] : \mem[6] [16];
  assign _0519_ = rd_ptr[1] ? _0518_ : _0517_;
  assign _0520_ = rd_ptr[2] ? _0519_ : _0516_;
  assign _0521_ = rd_ptr[0] ? \mem[9] [16] : \mem[8] [16];
  assign _0522_ = rd_ptr[0] ? \mem[11] [16] : \mem[10] [16];
  assign _0523_ = rd_ptr[1] ? _0522_ : _0521_;
  assign _0524_ = rd_ptr[0] ? \mem[13] [16] : \mem[12] [16];
  assign _0525_ = rd_ptr[0] ? \mem[15] [16] : \mem[14] [16];
  assign _0526_ = rd_ptr[1] ? _0525_ : _0524_;
  assign _0527_ = rd_ptr[2] ? _0526_ : _0523_;
  assign _0000_[16] = rd_ptr[3] ? _0527_ : _0520_;
  assign _0528_ = rd_ptr[0] ? \mem[1] [17] : \mem[0] [17];
  assign _0529_ = rd_ptr[0] ? \mem[3] [17] : \mem[2] [17];
  assign _0530_ = rd_ptr[1] ? _0529_ : _0528_;
  assign _0531_ = rd_ptr[0] ? \mem[5] [17] : \mem[4] [17];
  assign _0532_ = rd_ptr[0] ? \mem[7] [17] : \mem[6] [17];
  assign _0533_ = rd_ptr[1] ? _0532_ : _0531_;
  assign _0534_ = rd_ptr[2] ? _0533_ : _0530_;
  assign _0535_ = rd_ptr[0] ? \mem[9] [17] : \mem[8] [17];
  assign _0536_ = rd_ptr[0] ? \mem[11] [17] : \mem[10] [17];
  assign _0537_ = rd_ptr[1] ? _0536_ : _0535_;
  assign _0538_ = rd_ptr[0] ? \mem[13] [17] : \mem[12] [17];
  assign _0539_ = rd_ptr[0] ? \mem[15] [17] : \mem[14] [17];
  assign _0540_ = rd_ptr[1] ? _0539_ : _0538_;
  assign _0541_ = rd_ptr[2] ? _0540_ : _0537_;
  assign _0000_[17] = rd_ptr[3] ? _0541_ : _0534_;
  assign _0542_ = rd_ptr[0] ? \mem[1] [18] : \mem[0] [18];
  assign _0543_ = rd_ptr[0] ? \mem[3] [18] : \mem[2] [18];
  assign _0544_ = rd_ptr[1] ? _0543_ : _0542_;
  assign _0545_ = rd_ptr[0] ? \mem[5] [18] : \mem[4] [18];
  assign _0546_ = rd_ptr[0] ? \mem[7] [18] : \mem[6] [18];
  assign _0547_ = rd_ptr[1] ? _0546_ : _0545_;
  assign _0548_ = rd_ptr[2] ? _0547_ : _0544_;
  assign _0549_ = rd_ptr[0] ? \mem[9] [18] : \mem[8] [18];
  assign _0550_ = rd_ptr[0] ? \mem[11] [18] : \mem[10] [18];
  assign _0551_ = rd_ptr[1] ? _0550_ : _0549_;
  assign _0552_ = rd_ptr[0] ? \mem[13] [18] : \mem[12] [18];
  assign _0553_ = rd_ptr[0] ? \mem[15] [18] : \mem[14] [18];
  assign _0554_ = rd_ptr[1] ? _0553_ : _0552_;
  assign _0555_ = rd_ptr[2] ? _0554_ : _0551_;
  assign _0000_[18] = rd_ptr[3] ? _0555_ : _0548_;
  assign _0556_ = rd_ptr[0] ? \mem[1] [19] : \mem[0] [19];
  assign _0557_ = rd_ptr[0] ? \mem[3] [19] : \mem[2] [19];
  assign _0558_ = rd_ptr[1] ? _0557_ : _0556_;
  assign _0559_ = rd_ptr[0] ? \mem[5] [19] : \mem[4] [19];
  assign _0560_ = rd_ptr[0] ? \mem[7] [19] : \mem[6] [19];
  assign _0561_ = rd_ptr[1] ? _0560_ : _0559_;
  assign _0562_ = rd_ptr[2] ? _0561_ : _0558_;
  assign _0563_ = rd_ptr[0] ? \mem[9] [19] : \mem[8] [19];
  assign _0564_ = rd_ptr[0] ? \mem[11] [19] : \mem[10] [19];
  assign _0565_ = rd_ptr[1] ? _0564_ : _0563_;
  assign _0566_ = rd_ptr[0] ? \mem[13] [19] : \mem[12] [19];
  assign _0567_ = rd_ptr[0] ? \mem[15] [19] : \mem[14] [19];
  assign _0568_ = rd_ptr[1] ? _0567_ : _0566_;
  assign _0569_ = rd_ptr[2] ? _0568_ : _0565_;
  assign _0000_[19] = rd_ptr[3] ? _0569_ : _0562_;
  assign _0570_ = rd_ptr[0] ? \mem[1] [20] : \mem[0] [20];
  assign _0571_ = rd_ptr[0] ? \mem[3] [20] : \mem[2] [20];
  assign _0572_ = rd_ptr[1] ? _0571_ : _0570_;
  assign _0573_ = rd_ptr[0] ? \mem[5] [20] : \mem[4] [20];
  assign _0574_ = rd_ptr[0] ? \mem[7] [20] : \mem[6] [20];
  assign _0575_ = rd_ptr[1] ? _0574_ : _0573_;
  assign _0576_ = rd_ptr[2] ? _0575_ : _0572_;
  assign _0577_ = rd_ptr[0] ? \mem[9] [20] : \mem[8] [20];
  assign _0578_ = rd_ptr[0] ? \mem[11] [20] : \mem[10] [20];
  assign _0579_ = rd_ptr[1] ? _0578_ : _0577_;
  assign _0580_ = rd_ptr[0] ? \mem[13] [20] : \mem[12] [20];
  assign _0581_ = rd_ptr[0] ? \mem[15] [20] : \mem[14] [20];
  assign _0582_ = rd_ptr[1] ? _0581_ : _0580_;
  assign _0583_ = rd_ptr[2] ? _0582_ : _0579_;
  assign _0000_[20] = rd_ptr[3] ? _0583_ : _0576_;
  assign _0584_ = rd_ptr[0] ? \mem[1] [21] : \mem[0] [21];
  assign _0585_ = rd_ptr[0] ? \mem[3] [21] : \mem[2] [21];
  assign _0586_ = rd_ptr[1] ? _0585_ : _0584_;
  assign _0587_ = rd_ptr[0] ? \mem[5] [21] : \mem[4] [21];
  assign _0588_ = rd_ptr[0] ? \mem[7] [21] : \mem[6] [21];
  assign _0589_ = rd_ptr[1] ? _0588_ : _0587_;
  assign _0590_ = rd_ptr[2] ? _0589_ : _0586_;
  assign _0024_ = rd_ptr[0] ? \mem[9] [21] : \mem[8] [21];
  assign _0025_ = rd_ptr[0] ? \mem[11] [21] : \mem[10] [21];
  assign _0026_ = rd_ptr[1] ? _0025_ : _0024_;
  assign _0027_ = rd_ptr[0] ? \mem[13] [21] : \mem[12] [21];
  assign _0028_ = rd_ptr[0] ? \mem[15] [21] : \mem[14] [21];
  assign _0029_ = rd_ptr[1] ? _0028_ : _0027_;
  assign _0030_ = rd_ptr[2] ? _0029_ : _0026_;
  assign _0000_[21] = rd_ptr[3] ? _0030_ : _0590_;
  assign _0031_ = rd_ptr[0] ? \mem[1] [22] : \mem[0] [22];
  assign _0032_ = rd_ptr[0] ? \mem[3] [22] : \mem[2] [22];
  assign _0033_ = rd_ptr[1] ? _0032_ : _0031_;
  assign _0034_ = rd_ptr[0] ? \mem[5] [22] : \mem[4] [22];
  assign _0035_ = rd_ptr[0] ? \mem[7] [22] : \mem[6] [22];
  assign _0036_ = rd_ptr[1] ? _0035_ : _0034_;
  assign _0037_ = rd_ptr[2] ? _0036_ : _0033_;
  assign _0038_ = rd_ptr[0] ? \mem[9] [22] : \mem[8] [22];
  assign _0039_ = rd_ptr[0] ? \mem[11] [22] : \mem[10] [22];
  assign _0040_ = rd_ptr[1] ? _0039_ : _0038_;
  assign _0041_ = rd_ptr[0] ? \mem[13] [22] : \mem[12] [22];
  assign _0042_ = rd_ptr[0] ? \mem[15] [22] : \mem[14] [22];
  assign _0043_ = rd_ptr[1] ? _0042_ : _0041_;
  assign _0044_ = rd_ptr[2] ? _0043_ : _0040_;
  assign _0000_[22] = rd_ptr[3] ? _0044_ : _0037_;
  assign _0045_ = rd_ptr[0] ? \mem[1] [23] : \mem[0] [23];
  assign _0046_ = rd_ptr[0] ? \mem[3] [23] : \mem[2] [23];
  assign _0047_ = rd_ptr[1] ? _0046_ : _0045_;
  assign _0048_ = rd_ptr[0] ? \mem[5] [23] : \mem[4] [23];
  assign _0049_ = rd_ptr[0] ? \mem[7] [23] : \mem[6] [23];
  assign _0050_ = rd_ptr[1] ? _0049_ : _0048_;
  assign _0051_ = rd_ptr[2] ? _0050_ : _0047_;
  assign _0052_ = rd_ptr[0] ? \mem[9] [23] : \mem[8] [23];
  assign _0053_ = rd_ptr[0] ? \mem[11] [23] : \mem[10] [23];
  assign _0054_ = rd_ptr[1] ? _0053_ : _0052_;
  assign _0055_ = rd_ptr[0] ? \mem[13] [23] : \mem[12] [23];
  assign _0056_ = rd_ptr[0] ? \mem[15] [23] : \mem[14] [23];
  assign _0057_ = rd_ptr[1] ? _0056_ : _0055_;
  assign _0058_ = rd_ptr[2] ? _0057_ : _0054_;
  assign _0000_[23] = rd_ptr[3] ? _0058_ : _0051_;
  assign _0059_ = rd_ptr[0] ? \mem[1] [24] : \mem[0] [24];
  assign _0060_ = rd_ptr[0] ? \mem[3] [24] : \mem[2] [24];
  assign _0061_ = rd_ptr[1] ? _0060_ : _0059_;
  assign _0062_ = rd_ptr[0] ? \mem[5] [24] : \mem[4] [24];
  assign _0063_ = rd_ptr[0] ? \mem[7] [24] : \mem[6] [24];
  assign _0064_ = rd_ptr[1] ? _0063_ : _0062_;
  assign _0065_ = rd_ptr[2] ? _0064_ : _0061_;
  assign _0066_ = rd_ptr[0] ? \mem[9] [24] : \mem[8] [24];
  assign _0067_ = rd_ptr[0] ? \mem[11] [24] : \mem[10] [24];
  assign _0068_ = rd_ptr[1] ? _0067_ : _0066_;
  assign _0069_ = rd_ptr[0] ? \mem[13] [24] : \mem[12] [24];
  assign _0070_ = rd_ptr[0] ? \mem[15] [24] : \mem[14] [24];
  assign _0071_ = rd_ptr[1] ? _0070_ : _0069_;
  assign _0072_ = rd_ptr[2] ? _0071_ : _0068_;
  assign _0000_[24] = rd_ptr[3] ? _0072_ : _0065_;
  assign _0073_ = rd_ptr[0] ? \mem[1] [25] : \mem[0] [25];
  assign _0074_ = rd_ptr[0] ? \mem[3] [25] : \mem[2] [25];
  assign _0075_ = rd_ptr[1] ? _0074_ : _0073_;
  assign _0076_ = rd_ptr[0] ? \mem[5] [25] : \mem[4] [25];
  assign _0077_ = rd_ptr[0] ? \mem[7] [25] : \mem[6] [25];
  assign _0078_ = rd_ptr[1] ? _0077_ : _0076_;
  assign _0079_ = rd_ptr[2] ? _0078_ : _0075_;
  assign _0080_ = rd_ptr[0] ? \mem[9] [25] : \mem[8] [25];
  assign _0081_ = rd_ptr[0] ? \mem[11] [25] : \mem[10] [25];
  assign _0082_ = rd_ptr[1] ? _0081_ : _0080_;
  assign _0083_ = rd_ptr[0] ? \mem[13] [25] : \mem[12] [25];
  assign _0084_ = rd_ptr[0] ? \mem[15] [25] : \mem[14] [25];
  assign _0085_ = rd_ptr[1] ? _0084_ : _0083_;
  assign _0086_ = rd_ptr[2] ? _0085_ : _0082_;
  assign _0000_[25] = rd_ptr[3] ? _0086_ : _0079_;
  assign _0087_ = rd_ptr[0] ? \mem[1] [26] : \mem[0] [26];
  assign _0088_ = rd_ptr[0] ? \mem[3] [26] : \mem[2] [26];
  assign _0089_ = rd_ptr[1] ? _0088_ : _0087_;
  assign _0090_ = rd_ptr[0] ? \mem[5] [26] : \mem[4] [26];
  assign _0091_ = rd_ptr[0] ? \mem[7] [26] : \mem[6] [26];
  assign _0092_ = rd_ptr[1] ? _0091_ : _0090_;
  assign _0093_ = rd_ptr[2] ? _0092_ : _0089_;
  assign _0094_ = rd_ptr[0] ? \mem[9] [26] : \mem[8] [26];
  assign _0095_ = rd_ptr[0] ? \mem[11] [26] : \mem[10] [26];
  assign _0096_ = rd_ptr[1] ? _0095_ : _0094_;
  assign _0097_ = rd_ptr[0] ? \mem[13] [26] : \mem[12] [26];
  assign _0098_ = rd_ptr[0] ? \mem[15] [26] : \mem[14] [26];
  assign _0099_ = rd_ptr[1] ? _0098_ : _0097_;
  assign _0100_ = rd_ptr[2] ? _0099_ : _0096_;
  assign _0000_[26] = rd_ptr[3] ? _0100_ : _0093_;
  assign _0101_ = rd_ptr[0] ? \mem[1] [27] : \mem[0] [27];
  assign _0102_ = rd_ptr[0] ? \mem[3] [27] : \mem[2] [27];
  assign _0103_ = rd_ptr[1] ? _0102_ : _0101_;
  assign _0104_ = rd_ptr[0] ? \mem[5] [27] : \mem[4] [27];
  assign _0105_ = rd_ptr[0] ? \mem[7] [27] : \mem[6] [27];
  assign _0106_ = rd_ptr[1] ? _0105_ : _0104_;
  assign _0107_ = rd_ptr[2] ? _0106_ : _0103_;
  assign _0108_ = rd_ptr[0] ? \mem[9] [27] : \mem[8] [27];
  assign _0109_ = rd_ptr[0] ? \mem[11] [27] : \mem[10] [27];
  assign _0110_ = rd_ptr[1] ? _0109_ : _0108_;
  assign _0111_ = rd_ptr[0] ? \mem[13] [27] : \mem[12] [27];
  assign _0112_ = rd_ptr[0] ? \mem[15] [27] : \mem[14] [27];
  assign _0113_ = rd_ptr[1] ? _0112_ : _0111_;
  assign _0114_ = rd_ptr[2] ? _0113_ : _0110_;
  assign _0000_[27] = rd_ptr[3] ? _0114_ : _0107_;
  assign _0115_ = rd_ptr[0] ? \mem[1] [28] : \mem[0] [28];
  assign _0116_ = rd_ptr[0] ? \mem[3] [28] : \mem[2] [28];
  assign _0117_ = rd_ptr[1] ? _0116_ : _0115_;
  assign _0118_ = rd_ptr[0] ? \mem[5] [28] : \mem[4] [28];
  assign _0119_ = rd_ptr[0] ? \mem[7] [28] : \mem[6] [28];
  assign _0120_ = rd_ptr[1] ? _0119_ : _0118_;
  assign _0121_ = rd_ptr[2] ? _0120_ : _0117_;
  assign _0122_ = rd_ptr[0] ? \mem[9] [28] : \mem[8] [28];
  assign _0123_ = rd_ptr[0] ? \mem[11] [28] : \mem[10] [28];
  assign _0124_ = rd_ptr[1] ? _0123_ : _0122_;
  assign _0125_ = rd_ptr[0] ? \mem[13] [28] : \mem[12] [28];
  assign _0126_ = rd_ptr[0] ? \mem[15] [28] : \mem[14] [28];
  assign _0127_ = rd_ptr[1] ? _0126_ : _0125_;
  assign _0128_ = rd_ptr[2] ? _0127_ : _0124_;
  assign _0000_[28] = rd_ptr[3] ? _0128_ : _0121_;
  assign _0129_ = rd_ptr[0] ? \mem[1] [29] : \mem[0] [29];
  assign _0130_ = rd_ptr[0] ? \mem[3] [29] : \mem[2] [29];
  assign _0131_ = rd_ptr[1] ? _0130_ : _0129_;
  assign _0132_ = rd_ptr[0] ? \mem[5] [29] : \mem[4] [29];
  assign _0133_ = rd_ptr[0] ? \mem[7] [29] : \mem[6] [29];
  assign _0134_ = rd_ptr[1] ? _0133_ : _0132_;
  assign _0135_ = rd_ptr[2] ? _0134_ : _0131_;
  assign _0136_ = rd_ptr[0] ? \mem[9] [29] : \mem[8] [29];
  assign _0137_ = rd_ptr[0] ? \mem[11] [29] : \mem[10] [29];
  assign _0138_ = rd_ptr[1] ? _0137_ : _0136_;
  assign _0139_ = rd_ptr[0] ? \mem[13] [29] : \mem[12] [29];
  assign _0140_ = rd_ptr[0] ? \mem[15] [29] : \mem[14] [29];
  assign _0141_ = rd_ptr[1] ? _0140_ : _0139_;
  assign _0142_ = rd_ptr[2] ? _0141_ : _0138_;
  assign _0000_[29] = rd_ptr[3] ? _0142_ : _0135_;
  assign _0143_ = rd_ptr[0] ? \mem[1] [30] : \mem[0] [30];
  assign _0144_ = rd_ptr[0] ? \mem[3] [30] : \mem[2] [30];
  assign _0145_ = rd_ptr[1] ? _0144_ : _0143_;
  assign _0146_ = rd_ptr[0] ? \mem[5] [30] : \mem[4] [30];
  assign _0147_ = rd_ptr[0] ? \mem[7] [30] : \mem[6] [30];
  assign _0148_ = rd_ptr[1] ? _0147_ : _0146_;
  assign _0149_ = rd_ptr[2] ? _0148_ : _0145_;
  assign _0150_ = rd_ptr[0] ? \mem[9] [30] : \mem[8] [30];
  assign _0151_ = rd_ptr[0] ? \mem[11] [30] : \mem[10] [30];
  assign _0152_ = rd_ptr[1] ? _0151_ : _0150_;
  assign _0153_ = rd_ptr[0] ? \mem[13] [30] : \mem[12] [30];
  assign _0154_ = rd_ptr[0] ? \mem[15] [30] : \mem[14] [30];
  assign _0155_ = rd_ptr[1] ? _0154_ : _0153_;
  assign _0156_ = rd_ptr[2] ? _0155_ : _0152_;
  assign _0000_[30] = rd_ptr[3] ? _0156_ : _0149_;
  assign _0157_ = rd_ptr[0] ? \mem[1] [31] : \mem[0] [31];
  assign _0158_ = rd_ptr[0] ? \mem[3] [31] : \mem[2] [31];
  assign _0159_ = rd_ptr[1] ? _0158_ : _0157_;
  assign _0160_ = rd_ptr[0] ? \mem[5] [31] : \mem[4] [31];
  assign _0161_ = rd_ptr[0] ? \mem[7] [31] : \mem[6] [31];
  assign _0162_ = rd_ptr[1] ? _0161_ : _0160_;
  assign _0163_ = rd_ptr[2] ? _0162_ : _0159_;
  assign _0164_ = rd_ptr[0] ? \mem[9] [31] : \mem[8] [31];
  assign _0165_ = rd_ptr[0] ? \mem[11] [31] : \mem[10] [31];
  assign _0166_ = rd_ptr[1] ? _0165_ : _0164_;
  assign _0167_ = rd_ptr[0] ? \mem[13] [31] : \mem[12] [31];
  assign _0168_ = rd_ptr[0] ? \mem[15] [31] : \mem[14] [31];
  assign _0169_ = rd_ptr[1] ? _0168_ : _0167_;
  assign _0170_ = rd_ptr[2] ? _0169_ : _0166_;
  assign _0000_[31] = rd_ptr[3] ? _0170_ : _0163_;
  assign next_rd_ptr[0] = ~_0232_;
  assign next_rd_ptr[1] = ~_0236_;
  assign next_rd_ptr[2] = ~_0257_;
  assign next_rd_ptr[3] = ~_0252_;
  assign next_rd_ptr[4] = ~_0278_;
  assign next_wr_ptr[0] = ~_0230_;
  assign next_wr_ptr[3] = ~_0246_;
  assign next_wr_ptr[4] = ~_0273_;
  assign _0171_ = rd_ptr[0] ? \mem[1] [0] : \mem[0] [0];
  assign _0172_ = rd_ptr[0] ? \mem[3] [0] : \mem[2] [0];
  assign _0173_ = rd_ptr[1] ? _0172_ : _0171_;
  assign _0174_ = rd_ptr[0] ? \mem[5] [0] : \mem[4] [0];
  assign _0175_ = rd_ptr[0] ? \mem[7] [0] : \mem[6] [0];
  assign _0176_ = rd_ptr[1] ? _0175_ : _0174_;
  assign _0177_ = rd_ptr[2] ? _0176_ : _0173_;
  assign _0178_ = rd_ptr[0] ? \mem[9] [0] : \mem[8] [0];
  assign _0179_ = rd_ptr[0] ? \mem[11] [0] : \mem[10] [0];
  assign _0180_ = rd_ptr[1] ? _0179_ : _0178_;
  assign _0181_ = rd_ptr[0] ? \mem[13] [0] : \mem[12] [0];
  assign _0182_ = rd_ptr[0] ? \mem[15] [0] : \mem[14] [0];
  assign _0183_ = rd_ptr[1] ? _0182_ : _0181_;
  assign _0184_ = rd_ptr[2] ? _0183_ : _0180_;
  assign _0000_[0] = rd_ptr[3] ? _0184_ : _0177_;
  assign next_data_count[1] = ~_0239_;
  assign next_data_count[3] = ~_0265_;
  assign _0185_ = ~(wr_ptr[1] | wr_ptr[0]);
  assign _0186_ = wr_ptr[3] | wr_ptr[2];
  assign _0187_ = _0186_ | ~(_0185_);
  assign _0188_ = rst_n & ~(_0229_);
  assign _0008_ = _0188_ & ~(_0187_);
  assign _0189_ = wr_ptr[0] | ~(wr_ptr[1]);
  assign _0190_ = _0186_ | _0189_;
  assign _0016_ = _0188_ & ~(_0190_);
  assign _0191_ = _0186_ | ~(_0243_);
  assign _0017_ = _0188_ & ~(_0191_);
  assign _0192_ = wr_ptr[3] | ~(wr_ptr[2]);
  assign _0193_ = _0192_ | ~(_0185_);
  assign _0018_ = _0188_ & ~(_0193_);
  assign _0194_ = wr_ptr[1] | ~(wr_ptr[0]);
  assign _0195_ = _0192_ | _0194_;
  assign _0019_ = _0188_ & ~(_0195_);
  assign _0196_ = _0192_ | _0189_;
  assign _0020_ = _0188_ & ~(_0196_);
  assign _0197_ = _0192_ | ~(_0243_);
  assign _0021_ = _0188_ & ~(_0197_);
  assign _0198_ = wr_ptr[2] | ~(wr_ptr[3]);
  assign _0199_ = _0198_ | ~(_0185_);
  assign _0022_ = _0188_ & ~(_0199_);
  assign _0200_ = _0198_ | _0194_;
  assign _0023_ = _0188_ & ~(_0200_);
  assign _0201_ = _0286_ | peak_count[4];
  assign _0202_ = _0286_ ^ peak_count[4];
  assign _0203_ = _0265_ | peak_count[3];
  assign _0204_ = _0265_ ^ peak_count[3];
  assign _0205_ = _0266_ | peak_count[2];
  assign _0206_ = _0204_ & ~(_0205_);
  assign _0207_ = _0203_ & ~(_0206_);
  assign _0208_ = ~(_0266_ ^ peak_count[2]);
  assign _0209_ = _0208_ | ~(_0204_);
  assign _0210_ = _0239_ | peak_count[1];
  assign _0211_ = _0239_ ^ peak_count[1];
  assign _0212_ = peak_count[0] & ~(next_data_count[0]);
  assign _0213_ = _0211_ & ~(_0212_);
  assign _0214_ = _0213_ | ~(_0210_);
  assign _0215_ = _0214_ & ~(_0209_);
  assign _0216_ = _0207_ & ~(_0215_);
  assign _0217_ = _0202_ & ~(_0216_);
  assign _0218_ = _0201_ & ~(_0217_);
  assign _0219_ = ~(next_data_count[0] ^ peak_count[0]);
  assign _0220_ = ~(_0219_ & _0211_);
  assign _0221_ = _0220_ | _0209_;
  assign _0222_ = _0202_ & ~(_0221_);
  assign _0003_ = _0222_ | _0218_;
  assign _0223_ = _0198_ | _0189_;
  assign _0009_ = _0188_ & ~(_0223_);
  assign _0224_ = _0198_ | ~(_0243_);
  assign _0010_ = _0188_ & ~(_0224_);
  assign _0225_ = _0270_ | ~(_0185_);
  assign _0011_ = _0188_ & ~(_0225_);
  assign _0226_ = _0270_ | _0194_;
  assign _0012_ = _0188_ & ~(_0226_);
  assign _0227_ = _0270_ | _0189_;
  assign _0013_ = _0188_ & ~(_0227_);
  assign _0014_ = _0188_ & _0271_;
  assign _0228_ = _0186_ | _0194_;
  assign _0015_ = _0188_ & ~(_0228_);
  always @(posedge clk)
    if (_0009_) \mem[10] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0009_) \mem[10] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0009_) \mem[10] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0009_) \mem[10] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0009_) \mem[10] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0009_) \mem[10] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0009_) \mem[10] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0009_) \mem[10] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0009_) \mem[10] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0009_) \mem[10] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0009_) \mem[10] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0009_) \mem[10] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0009_) \mem[10] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0009_) \mem[10] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0009_) \mem[10] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0009_) \mem[10] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0009_) \mem[10] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0009_) \mem[10] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0009_) \mem[10] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0009_) \mem[10] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0009_) \mem[10] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0009_) \mem[10] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0009_) \mem[10] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0009_) \mem[10] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0009_) \mem[10] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0009_) \mem[10] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0009_) \mem[10] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0009_) \mem[10] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0009_) \mem[10] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0009_) \mem[10] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0009_) \mem[10] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0009_) \mem[10] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0019_) \mem[5] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0019_) \mem[5] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0019_) \mem[5] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0019_) \mem[5] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0019_) \mem[5] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0019_) \mem[5] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0019_) \mem[5] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0019_) \mem[5] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0019_) \mem[5] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0019_) \mem[5] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0019_) \mem[5] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0019_) \mem[5] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0019_) \mem[5] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0019_) \mem[5] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0019_) \mem[5] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0019_) \mem[5] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0019_) \mem[5] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0019_) \mem[5] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0019_) \mem[5] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0019_) \mem[5] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0019_) \mem[5] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0019_) \mem[5] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0019_) \mem[5] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0019_) \mem[5] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0019_) \mem[5] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0019_) \mem[5] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0019_) \mem[5] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0019_) \mem[5] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0019_) \mem[5] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0019_) \mem[5] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0019_) \mem[5] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0019_) \mem[5] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0018_) \mem[4] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0018_) \mem[4] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0018_) \mem[4] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0018_) \mem[4] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0018_) \mem[4] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0018_) \mem[4] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0018_) \mem[4] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0018_) \mem[4] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0018_) \mem[4] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0018_) \mem[4] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0018_) \mem[4] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0018_) \mem[4] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0018_) \mem[4] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0018_) \mem[4] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0018_) \mem[4] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0018_) \mem[4] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0018_) \mem[4] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0018_) \mem[4] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0018_) \mem[4] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0018_) \mem[4] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0018_) \mem[4] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0018_) \mem[4] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0018_) \mem[4] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0018_) \mem[4] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0018_) \mem[4] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0018_) \mem[4] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0018_) \mem[4] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0018_) \mem[4] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0018_) \mem[4] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0018_) \mem[4] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0018_) \mem[4] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0018_) \mem[4] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0017_) \mem[3] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0017_) \mem[3] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0017_) \mem[3] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0017_) \mem[3] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0017_) \mem[3] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0017_) \mem[3] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0017_) \mem[3] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0017_) \mem[3] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0017_) \mem[3] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0017_) \mem[3] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0017_) \mem[3] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0017_) \mem[3] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0017_) \mem[3] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0017_) \mem[3] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0017_) \mem[3] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0017_) \mem[3] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0017_) \mem[3] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0017_) \mem[3] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0017_) \mem[3] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0017_) \mem[3] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0017_) \mem[3] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0017_) \mem[3] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0017_) \mem[3] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0017_) \mem[3] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0017_) \mem[3] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0017_) \mem[3] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0017_) \mem[3] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0017_) \mem[3] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0017_) \mem[3] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0017_) \mem[3] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0017_) \mem[3] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0017_) \mem[3] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0016_) \mem[2] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0016_) \mem[2] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0016_) \mem[2] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0016_) \mem[2] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0016_) \mem[2] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0016_) \mem[2] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0016_) \mem[2] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0016_) \mem[2] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0016_) \mem[2] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0016_) \mem[2] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0016_) \mem[2] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0016_) \mem[2] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0016_) \mem[2] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0016_) \mem[2] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0016_) \mem[2] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0016_) \mem[2] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0016_) \mem[2] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0016_) \mem[2] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0016_) \mem[2] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0016_) \mem[2] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0016_) \mem[2] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0016_) \mem[2] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0016_) \mem[2] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0016_) \mem[2] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0016_) \mem[2] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0016_) \mem[2] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0016_) \mem[2] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0016_) \mem[2] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0016_) \mem[2] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0016_) \mem[2] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0016_) \mem[2] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0016_) \mem[2] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0015_) \mem[1] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0015_) \mem[1] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0015_) \mem[1] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0015_) \mem[1] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0015_) \mem[1] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0015_) \mem[1] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0015_) \mem[1] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0015_) \mem[1] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0015_) \mem[1] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0015_) \mem[1] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0015_) \mem[1] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0015_) \mem[1] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0015_) \mem[1] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0015_) \mem[1] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0015_) \mem[1] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0015_) \mem[1] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0015_) \mem[1] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0015_) \mem[1] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0015_) \mem[1] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0015_) \mem[1] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0015_) \mem[1] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0015_) \mem[1] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0015_) \mem[1] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0015_) \mem[1] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0015_) \mem[1] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0015_) \mem[1] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0015_) \mem[1] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0015_) \mem[1] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0015_) \mem[1] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0015_) \mem[1] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0015_) \mem[1] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0015_) \mem[1] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0014_) \mem[15] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0014_) \mem[15] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0014_) \mem[15] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0014_) \mem[15] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0014_) \mem[15] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0014_) \mem[15] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0014_) \mem[15] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0014_) \mem[15] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0014_) \mem[15] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0014_) \mem[15] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0014_) \mem[15] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0014_) \mem[15] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0014_) \mem[15] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0014_) \mem[15] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0014_) \mem[15] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0014_) \mem[15] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0014_) \mem[15] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0014_) \mem[15] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0014_) \mem[15] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0014_) \mem[15] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0014_) \mem[15] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0014_) \mem[15] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0014_) \mem[15] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0014_) \mem[15] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0014_) \mem[15] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0014_) \mem[15] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0014_) \mem[15] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0014_) \mem[15] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0014_) \mem[15] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0014_) \mem[15] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0014_) \mem[15] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0014_) \mem[15] [31] <= wr_data[31];
  always @(posedge clk)
    if (!rst_n) peak_count[0] <= 1'h0;
    else if (!_0003_) peak_count[0] <= next_data_count[0];
  always @(posedge clk)
    if (!rst_n) peak_count[1] <= 1'h0;
    else if (!_0003_) peak_count[1] <= next_data_count[1];
  always @(posedge clk)
    if (!rst_n) peak_count[2] <= 1'h0;
    else if (!_0003_) peak_count[2] <= next_data_count[2];
  always @(posedge clk)
    if (!rst_n) peak_count[3] <= 1'h0;
    else if (!_0003_) peak_count[3] <= next_data_count[3];
  always @(posedge clk)
    if (!rst_n) peak_count[4] <= 1'h0;
    else if (!_0003_) peak_count[4] <= next_data_count[4];
  always @(posedge clk)
    if (!rst_n) overflow <= 1'h0;
    else overflow <= _0006_;
  always @(posedge clk)
    if (!rst_n) underflow <= 1'h0;
    else underflow <= _0007_;
  always @(posedge clk)
    if (!rst_n) full <= 1'h0;
    else full <= _0005_;
  always @(posedge clk)
    if (!rst_n) almost_full <= 1'h0;
    else almost_full <= _0002_;
  always @(posedge clk)
    if (!rst_n) empty <= 1'h1;
    else empty <= _0004_;
  always @(posedge clk)
    if (!rst_n) almost_empty <= 1'h1;
    else almost_empty <= _0001_;
  always @(posedge clk)
    if (!rst_n) data_count[0] <= 1'h0;
    else data_count[0] <= next_data_count[0];
  always @(posedge clk)
    if (!rst_n) data_count[1] <= 1'h0;
    else data_count[1] <= next_data_count[1];
  always @(posedge clk)
    if (!rst_n) data_count[2] <= 1'h0;
    else data_count[2] <= next_data_count[2];
  always @(posedge clk)
    if (!rst_n) data_count[3] <= 1'h0;
    else data_count[3] <= next_data_count[3];
  always @(posedge clk)
    if (!rst_n) data_count[4] <= 1'h0;
    else data_count[4] <= next_data_count[4];
  always @(posedge clk)
    if (!rst_n) rd_ptr[0] <= 1'h0;
    else rd_ptr[0] <= next_rd_ptr[0];
  always @(posedge clk)
    if (!rst_n) rd_ptr[1] <= 1'h0;
    else rd_ptr[1] <= next_rd_ptr[1];
  always @(posedge clk)
    if (!rst_n) rd_ptr[2] <= 1'h0;
    else rd_ptr[2] <= next_rd_ptr[2];
  always @(posedge clk)
    if (!rst_n) rd_ptr[3] <= 1'h0;
    else rd_ptr[3] <= next_rd_ptr[3];
  always @(posedge clk)
    if (!rst_n) rd_ptr[4] <= 1'h0;
    else rd_ptr[4] <= next_rd_ptr[4];
  always @(posedge clk)
    if (_0008_) \mem[0] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0008_) \mem[0] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0008_) \mem[0] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0008_) \mem[0] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0008_) \mem[0] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0008_) \mem[0] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0008_) \mem[0] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0008_) \mem[0] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0008_) \mem[0] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0008_) \mem[0] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0008_) \mem[0] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0008_) \mem[0] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0008_) \mem[0] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0008_) \mem[0] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0008_) \mem[0] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0008_) \mem[0] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0008_) \mem[0] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0008_) \mem[0] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0008_) \mem[0] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0008_) \mem[0] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0008_) \mem[0] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0008_) \mem[0] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0008_) \mem[0] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0008_) \mem[0] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0008_) \mem[0] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0008_) \mem[0] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0008_) \mem[0] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0008_) \mem[0] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0008_) \mem[0] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0008_) \mem[0] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0008_) \mem[0] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0008_) \mem[0] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0023_) \mem[9] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0023_) \mem[9] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0023_) \mem[9] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0023_) \mem[9] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0023_) \mem[9] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0023_) \mem[9] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0023_) \mem[9] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0023_) \mem[9] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0023_) \mem[9] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0023_) \mem[9] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0023_) \mem[9] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0023_) \mem[9] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0023_) \mem[9] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0023_) \mem[9] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0023_) \mem[9] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0023_) \mem[9] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0023_) \mem[9] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0023_) \mem[9] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0023_) \mem[9] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0023_) \mem[9] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0023_) \mem[9] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0023_) \mem[9] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0023_) \mem[9] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0023_) \mem[9] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0023_) \mem[9] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0023_) \mem[9] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0023_) \mem[9] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0023_) \mem[9] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0023_) \mem[9] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0023_) \mem[9] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0023_) \mem[9] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0023_) \mem[9] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0022_) \mem[8] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0022_) \mem[8] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0022_) \mem[8] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0022_) \mem[8] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0022_) \mem[8] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0022_) \mem[8] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0022_) \mem[8] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0022_) \mem[8] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0022_) \mem[8] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0022_) \mem[8] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0022_) \mem[8] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0022_) \mem[8] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0022_) \mem[8] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0022_) \mem[8] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0022_) \mem[8] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0022_) \mem[8] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0022_) \mem[8] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0022_) \mem[8] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0022_) \mem[8] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0022_) \mem[8] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0022_) \mem[8] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0022_) \mem[8] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0022_) \mem[8] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0022_) \mem[8] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0022_) \mem[8] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0022_) \mem[8] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0022_) \mem[8] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0022_) \mem[8] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0022_) \mem[8] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0022_) \mem[8] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0022_) \mem[8] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0022_) \mem[8] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0021_) \mem[7] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0021_) \mem[7] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0021_) \mem[7] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0021_) \mem[7] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0021_) \mem[7] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0021_) \mem[7] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0021_) \mem[7] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0021_) \mem[7] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0021_) \mem[7] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0021_) \mem[7] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0021_) \mem[7] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0021_) \mem[7] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0021_) \mem[7] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0021_) \mem[7] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0021_) \mem[7] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0021_) \mem[7] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0021_) \mem[7] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0021_) \mem[7] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0021_) \mem[7] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0021_) \mem[7] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0021_) \mem[7] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0021_) \mem[7] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0021_) \mem[7] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0021_) \mem[7] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0021_) \mem[7] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0021_) \mem[7] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0021_) \mem[7] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0021_) \mem[7] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0021_) \mem[7] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0021_) \mem[7] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0021_) \mem[7] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0021_) \mem[7] [31] <= wr_data[31];
  always @(posedge clk)
    if (!rst_n) wr_ptr[0] <= 1'h0;
    else wr_ptr[0] <= next_wr_ptr[0];
  always @(posedge clk)
    if (!rst_n) wr_ptr[1] <= 1'h0;
    else wr_ptr[1] <= next_wr_ptr[1];
  always @(posedge clk)
    if (!rst_n) wr_ptr[2] <= 1'h0;
    else wr_ptr[2] <= next_wr_ptr[2];
  always @(posedge clk)
    if (!rst_n) wr_ptr[3] <= 1'h0;
    else wr_ptr[3] <= next_wr_ptr[3];
  always @(posedge clk)
    if (!rst_n) wr_ptr[4] <= 1'h0;
    else wr_ptr[4] <= next_wr_ptr[4];
  always @(posedge clk)
    if (_0020_) \mem[6] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0020_) \mem[6] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0020_) \mem[6] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0020_) \mem[6] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0020_) \mem[6] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0020_) \mem[6] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0020_) \mem[6] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0020_) \mem[6] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0020_) \mem[6] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0020_) \mem[6] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0020_) \mem[6] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0020_) \mem[6] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0020_) \mem[6] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0020_) \mem[6] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0020_) \mem[6] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0020_) \mem[6] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0020_) \mem[6] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0020_) \mem[6] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0020_) \mem[6] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0020_) \mem[6] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0020_) \mem[6] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0020_) \mem[6] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0020_) \mem[6] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0020_) \mem[6] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0020_) \mem[6] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0020_) \mem[6] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0020_) \mem[6] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0020_) \mem[6] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0020_) \mem[6] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0020_) \mem[6] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0020_) \mem[6] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0020_) \mem[6] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0011_) \mem[12] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0011_) \mem[12] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0011_) \mem[12] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0011_) \mem[12] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0011_) \mem[12] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0011_) \mem[12] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0011_) \mem[12] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0011_) \mem[12] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0011_) \mem[12] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0011_) \mem[12] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0011_) \mem[12] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0011_) \mem[12] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0011_) \mem[12] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0011_) \mem[12] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0011_) \mem[12] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0011_) \mem[12] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0011_) \mem[12] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0011_) \mem[12] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0011_) \mem[12] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0011_) \mem[12] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0011_) \mem[12] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0011_) \mem[12] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0011_) \mem[12] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0011_) \mem[12] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0011_) \mem[12] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0011_) \mem[12] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0011_) \mem[12] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0011_) \mem[12] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0011_) \mem[12] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0011_) \mem[12] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0011_) \mem[12] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0011_) \mem[12] [31] <= wr_data[31];
  always @(posedge clk)
    if (!rst_n) rd_data[0] <= 1'h0;
    else if (!_0231_) rd_data[0] <= _0000_[0];
  always @(posedge clk)
    if (!rst_n) rd_data[1] <= 1'h0;
    else if (!_0231_) rd_data[1] <= _0000_[1];
  always @(posedge clk)
    if (!rst_n) rd_data[2] <= 1'h0;
    else if (!_0231_) rd_data[2] <= _0000_[2];
  always @(posedge clk)
    if (!rst_n) rd_data[3] <= 1'h0;
    else if (!_0231_) rd_data[3] <= _0000_[3];
  always @(posedge clk)
    if (!rst_n) rd_data[4] <= 1'h0;
    else if (!_0231_) rd_data[4] <= _0000_[4];
  always @(posedge clk)
    if (!rst_n) rd_data[5] <= 1'h0;
    else if (!_0231_) rd_data[5] <= _0000_[5];
  always @(posedge clk)
    if (!rst_n) rd_data[6] <= 1'h0;
    else if (!_0231_) rd_data[6] <= _0000_[6];
  always @(posedge clk)
    if (!rst_n) rd_data[7] <= 1'h0;
    else if (!_0231_) rd_data[7] <= _0000_[7];
  always @(posedge clk)
    if (!rst_n) rd_data[8] <= 1'h0;
    else if (!_0231_) rd_data[8] <= _0000_[8];
  always @(posedge clk)
    if (!rst_n) rd_data[9] <= 1'h0;
    else if (!_0231_) rd_data[9] <= _0000_[9];
  always @(posedge clk)
    if (!rst_n) rd_data[10] <= 1'h0;
    else if (!_0231_) rd_data[10] <= _0000_[10];
  always @(posedge clk)
    if (!rst_n) rd_data[11] <= 1'h0;
    else if (!_0231_) rd_data[11] <= _0000_[11];
  always @(posedge clk)
    if (!rst_n) rd_data[12] <= 1'h0;
    else if (!_0231_) rd_data[12] <= _0000_[12];
  always @(posedge clk)
    if (!rst_n) rd_data[13] <= 1'h0;
    else if (!_0231_) rd_data[13] <= _0000_[13];
  always @(posedge clk)
    if (!rst_n) rd_data[14] <= 1'h0;
    else if (!_0231_) rd_data[14] <= _0000_[14];
  always @(posedge clk)
    if (!rst_n) rd_data[15] <= 1'h0;
    else if (!_0231_) rd_data[15] <= _0000_[15];
  always @(posedge clk)
    if (!rst_n) rd_data[16] <= 1'h0;
    else if (!_0231_) rd_data[16] <= _0000_[16];
  always @(posedge clk)
    if (!rst_n) rd_data[17] <= 1'h0;
    else if (!_0231_) rd_data[17] <= _0000_[17];
  always @(posedge clk)
    if (!rst_n) rd_data[18] <= 1'h0;
    else if (!_0231_) rd_data[18] <= _0000_[18];
  always @(posedge clk)
    if (!rst_n) rd_data[19] <= 1'h0;
    else if (!_0231_) rd_data[19] <= _0000_[19];
  always @(posedge clk)
    if (!rst_n) rd_data[20] <= 1'h0;
    else if (!_0231_) rd_data[20] <= _0000_[20];
  always @(posedge clk)
    if (!rst_n) rd_data[21] <= 1'h0;
    else if (!_0231_) rd_data[21] <= _0000_[21];
  always @(posedge clk)
    if (!rst_n) rd_data[22] <= 1'h0;
    else if (!_0231_) rd_data[22] <= _0000_[22];
  always @(posedge clk)
    if (!rst_n) rd_data[23] <= 1'h0;
    else if (!_0231_) rd_data[23] <= _0000_[23];
  always @(posedge clk)
    if (!rst_n) rd_data[24] <= 1'h0;
    else if (!_0231_) rd_data[24] <= _0000_[24];
  always @(posedge clk)
    if (!rst_n) rd_data[25] <= 1'h0;
    else if (!_0231_) rd_data[25] <= _0000_[25];
  always @(posedge clk)
    if (!rst_n) rd_data[26] <= 1'h0;
    else if (!_0231_) rd_data[26] <= _0000_[26];
  always @(posedge clk)
    if (!rst_n) rd_data[27] <= 1'h0;
    else if (!_0231_) rd_data[27] <= _0000_[27];
  always @(posedge clk)
    if (!rst_n) rd_data[28] <= 1'h0;
    else if (!_0231_) rd_data[28] <= _0000_[28];
  always @(posedge clk)
    if (!rst_n) rd_data[29] <= 1'h0;
    else if (!_0231_) rd_data[29] <= _0000_[29];
  always @(posedge clk)
    if (!rst_n) rd_data[30] <= 1'h0;
    else if (!_0231_) rd_data[30] <= _0000_[30];
  always @(posedge clk)
    if (!rst_n) rd_data[31] <= 1'h0;
    else if (!_0231_) rd_data[31] <= _0000_[31];
  always @(posedge clk)
    if (_0010_) \mem[11] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0010_) \mem[11] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0010_) \mem[11] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0010_) \mem[11] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0010_) \mem[11] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0010_) \mem[11] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0010_) \mem[11] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0010_) \mem[11] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0010_) \mem[11] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0010_) \mem[11] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0010_) \mem[11] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0010_) \mem[11] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0010_) \mem[11] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0010_) \mem[11] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0010_) \mem[11] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0010_) \mem[11] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0010_) \mem[11] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0010_) \mem[11] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0010_) \mem[11] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0010_) \mem[11] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0010_) \mem[11] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0010_) \mem[11] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0010_) \mem[11] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0010_) \mem[11] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0010_) \mem[11] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0010_) \mem[11] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0010_) \mem[11] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0010_) \mem[11] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0010_) \mem[11] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0010_) \mem[11] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0010_) \mem[11] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0010_) \mem[11] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0013_) \mem[14] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0013_) \mem[14] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0013_) \mem[14] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0013_) \mem[14] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0013_) \mem[14] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0013_) \mem[14] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0013_) \mem[14] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0013_) \mem[14] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0013_) \mem[14] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0013_) \mem[14] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0013_) \mem[14] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0013_) \mem[14] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0013_) \mem[14] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0013_) \mem[14] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0013_) \mem[14] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0013_) \mem[14] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0013_) \mem[14] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0013_) \mem[14] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0013_) \mem[14] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0013_) \mem[14] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0013_) \mem[14] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0013_) \mem[14] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0013_) \mem[14] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0013_) \mem[14] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0013_) \mem[14] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0013_) \mem[14] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0013_) \mem[14] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0013_) \mem[14] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0013_) \mem[14] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0013_) \mem[14] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0013_) \mem[14] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0013_) \mem[14] [31] <= wr_data[31];
  always @(posedge clk)
    if (_0012_) \mem[13] [0] <= wr_data[0];
  always @(posedge clk)
    if (_0012_) \mem[13] [1] <= wr_data[1];
  always @(posedge clk)
    if (_0012_) \mem[13] [2] <= wr_data[2];
  always @(posedge clk)
    if (_0012_) \mem[13] [3] <= wr_data[3];
  always @(posedge clk)
    if (_0012_) \mem[13] [4] <= wr_data[4];
  always @(posedge clk)
    if (_0012_) \mem[13] [5] <= wr_data[5];
  always @(posedge clk)
    if (_0012_) \mem[13] [6] <= wr_data[6];
  always @(posedge clk)
    if (_0012_) \mem[13] [7] <= wr_data[7];
  always @(posedge clk)
    if (_0012_) \mem[13] [8] <= wr_data[8];
  always @(posedge clk)
    if (_0012_) \mem[13] [9] <= wr_data[9];
  always @(posedge clk)
    if (_0012_) \mem[13] [10] <= wr_data[10];
  always @(posedge clk)
    if (_0012_) \mem[13] [11] <= wr_data[11];
  always @(posedge clk)
    if (_0012_) \mem[13] [12] <= wr_data[12];
  always @(posedge clk)
    if (_0012_) \mem[13] [13] <= wr_data[13];
  always @(posedge clk)
    if (_0012_) \mem[13] [14] <= wr_data[14];
  always @(posedge clk)
    if (_0012_) \mem[13] [15] <= wr_data[15];
  always @(posedge clk)
    if (_0012_) \mem[13] [16] <= wr_data[16];
  always @(posedge clk)
    if (_0012_) \mem[13] [17] <= wr_data[17];
  always @(posedge clk)
    if (_0012_) \mem[13] [18] <= wr_data[18];
  always @(posedge clk)
    if (_0012_) \mem[13] [19] <= wr_data[19];
  always @(posedge clk)
    if (_0012_) \mem[13] [20] <= wr_data[20];
  always @(posedge clk)
    if (_0012_) \mem[13] [21] <= wr_data[21];
  always @(posedge clk)
    if (_0012_) \mem[13] [22] <= wr_data[22];
  always @(posedge clk)
    if (_0012_) \mem[13] [23] <= wr_data[23];
  always @(posedge clk)
    if (_0012_) \mem[13] [24] <= wr_data[24];
  always @(posedge clk)
    if (_0012_) \mem[13] [25] <= wr_data[25];
  always @(posedge clk)
    if (_0012_) \mem[13] [26] <= wr_data[26];
  always @(posedge clk)
    if (_0012_) \mem[13] [27] <= wr_data[27];
  always @(posedge clk)
    if (_0012_) \mem[13] [28] <= wr_data[28];
  always @(posedge clk)
    if (_0012_) \mem[13] [29] <= wr_data[29];
  always @(posedge clk)
    if (_0012_) \mem[13] [30] <= wr_data[30];
  always @(posedge clk)
    if (_0012_) \mem[13] [31] <= wr_data[31];
  assign rd_addr = rd_ptr[3:0];
  assign wr_addr = wr_ptr[3:0];
endmodule
