/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module \$paramod$2d1f5da734bda88c85121ae0bcafa174ce0747b6\synchronizer (clk, rst_n, async_in, sync_out);
  input [4:0] async_in;
  wire [4:0] async_in;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  reg [4:0] \sync_chain[0] ;
  reg [4:0] \sync_chain[1] ;
  output [4:0] sync_out;
  wire [4:0] sync_out;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[0] [0] <= 1'h0;
    else \sync_chain[0] [0] <= async_in[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[0] [1] <= 1'h0;
    else \sync_chain[0] [1] <= async_in[1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[0] [2] <= 1'h0;
    else \sync_chain[0] [2] <= async_in[2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[0] [3] <= 1'h0;
    else \sync_chain[0] [3] <= async_in[3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[0] [4] <= 1'h0;
    else \sync_chain[0] [4] <= async_in[4];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[1] [0] <= 1'h0;
    else \sync_chain[1] [0] <= \sync_chain[0] [0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[1] [1] <= 1'h0;
    else \sync_chain[1] [1] <= \sync_chain[0] [1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[1] [2] <= 1'h0;
    else \sync_chain[1] [2] <= \sync_chain[0] [2];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[1] [3] <= 1'h0;
    else \sync_chain[1] [3] <= \sync_chain[0] [3];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \sync_chain[1] [4] <= 1'h0;
    else \sync_chain[1] [4] <= \sync_chain[0] [4];
  assign sync_out = \sync_chain[1] ;
endmodule

module fifo_async(wr_clk, wr_rst_n, wr_en, wr_data, full, almost_full, overflow, wr_data_count, rd_clk, rd_rst_n, rd_en, rd_data, empty, almost_empty, underflow, rd_data_count);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire [31:0] _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire [31:0] _0625_;
  wire [31:0] _0626_;
  output almost_empty;
  reg almost_empty;
  output almost_full;
  reg almost_full;
  wire [4:0] \bin2gray$func$../rtl/fifo_async.v:236$19.$result ;
  wire [4:0] \bin2gray$func$../rtl/fifo_async.v:236$23.binary ;
  wire [4:0] \bin2gray$func$../rtl/fifo_async.v:267$20.$result ;
  wire [4:0] \bin2gray$func$../rtl/fifo_async.v:267$24.binary ;
  wire do_read;
  wire do_write;
  output empty;
  reg empty;
  output full;
  reg full;
  wire [4:0] \gray2bin$func$../rtl/fifo_async.v:321$25.gray ;
  wire [31:0] \gray2bin$func$../rtl/fifo_async.v:321$25.i ;
  wire [4:0] \gray2bin$func$../rtl/fifo_async.v:322$26.gray ;
  wire [31:0] \gray2bin$func$../rtl/fifo_async.v:322$26.i ;
  reg [31:0] \mem[0] ;
  reg [31:0] \mem[10] ;
  reg [31:0] \mem[11] ;
  reg [31:0] \mem[12] ;
  reg [31:0] \mem[13] ;
  reg [31:0] \mem[14] ;
  reg [31:0] \mem[15] ;
  reg [31:0] \mem[1] ;
  reg [31:0] \mem[2] ;
  reg [31:0] \mem[3] ;
  reg [31:0] \mem[4] ;
  reg [31:0] \mem[5] ;
  reg [31:0] \mem[6] ;
  reg [31:0] \mem[7] ;
  reg [31:0] \mem[8] ;
  reg [31:0] \mem[9] ;
  output overflow;
  reg overflow;
  wire [3:0] rd_addr;
  input rd_clk;
  wire rd_clk;
  output [31:0] rd_data;
  reg [31:0] rd_data;
  output [4:0] rd_data_count;
  reg [4:0] rd_data_count;
  input rd_en;
  wire rd_en;
  wire [4:0] rd_ptr_bin;
  wire [4:0] rd_ptr_bin_next;
  wire [4:0] rd_ptr_bin_sync;
  reg [4:0] rd_ptr_gray;
  wire [4:0] rd_ptr_gray_next;
  wire [4:0] rd_ptr_gray_sync;
  input rd_rst_n;
  wire rd_rst_n;
  output underflow;
  reg underflow;
  wire [3:0] wr_addr;
  input wr_clk;
  wire wr_clk;
  input [31:0] wr_data;
  wire [31:0] wr_data;
  output [4:0] wr_data_count;
  reg [4:0] wr_data_count;
  input wr_en;
  wire wr_en;
  wire [4:0] wr_ptr_bin;
  wire [4:0] wr_ptr_bin_next;
  wire [4:0] wr_ptr_bin_sync;
  reg [4:0] wr_ptr_gray;
  wire [4:0] wr_ptr_gray_next;
  wire [4:0] wr_ptr_gray_sync;
  input wr_rst_n;
  wire wr_rst_n;
  assign wr_ptr_bin_next[0] = ~wr_ptr_bin[0];
  assign _0296_ = ~(rd_ptr_gray_sync[3] ^ rd_ptr_gray_sync[4]);
  assign _0297_ = _0296_ ^ rd_ptr_gray_sync[2];
  assign _0298_ = _0297_ ^ rd_ptr_gray_sync[1];
  assign _0299_ = _0298_ ^ rd_ptr_gray_sync[0];
  assign _0626_[0] = _0299_ ^ wr_ptr_bin_next[0];
  assign _0300_ = ~(wr_ptr_gray_sync[4] ^ wr_ptr_gray_sync[3]);
  assign _0301_ = _0300_ ^ wr_ptr_gray_sync[2];
  assign _0302_ = _0301_ ^ wr_ptr_gray_sync[1];
  assign _0303_ = ~(_0302_ ^ wr_ptr_gray_sync[0]);
  assign _0625_[0] = _0303_ ^ rd_ptr_bin[0];
  assign _0304_ = _0302_ ^ rd_ptr_bin[1];
  assign _0305_ = rd_ptr_bin[0] & ~(_0303_);
  assign _0306_ = _0305_ ^ _0304_;
  assign _0625_[1] = ~_0306_;
  assign _0307_ = wr_ptr_gray_sync[4] & ~(rd_ptr_gray[4]);
  assign _0308_ = wr_ptr_gray_sync[4] ^ rd_ptr_gray[4];
  assign _0309_ = _0300_ | rd_ptr_bin[3];
  assign _0310_ = ~rd_ptr_bin[3];
  assign _0311_ = _0300_ ^ _0310_;
  assign _0312_ = _0301_ | rd_ptr_bin[2];
  assign _0313_ = ~(_0312_ | _0311_);
  assign _0314_ = _0309_ & ~(_0313_);
  assign _0315_ = ~rd_ptr_bin[1];
  assign _0316_ = _0315_ & ~(_0302_);
  assign _0317_ = _0304_ & ~(_0305_);
  assign _0318_ = _0317_ | _0316_;
  assign _0319_ = ~rd_ptr_bin[2];
  assign _0320_ = _0301_ ^ _0319_;
  assign _0321_ = _0320_ | _0311_;
  assign _0322_ = _0318_ & ~(_0321_);
  assign _0323_ = _0314_ & ~(_0322_);
  assign _0324_ = ~(_0323_ | _0308_);
  assign _0325_ = _0324_ | _0307_;
  assign _0326_ = _0306_ | _0625_[0];
  assign _0625_[2] = ~(_0320_ ^ _0318_);
  assign _0327_ = _0318_ & ~(_0320_);
  assign _0328_ = _0312_ & ~(_0327_);
  assign _0625_[3] = _0328_ ^ _0311_;
  assign _0329_ = _0625_[3] | _0625_[2];
  assign _0330_ = _0329_ | _0326_;
  assign _0625_[4] = _0323_ ^ _0308_;
  assign _0331_ = _0625_[4] | ~(_0325_);
  assign _0332_ = _0331_ | _0330_;
  assign _0333_ = _0325_ & ~(_0332_);
  assign _0334_ = _0625_[0] & ~(_0306_);
  assign _0335_ = _0334_ | _0329_;
  assign _0336_ = _0335_ | _0331_;
  assign _0337_ = _0325_ & ~(_0336_);
  assign _0000_ = _0337_ | _0333_;
  assign _0338_ = rd_ptr_gray_sync[4] | ~(wr_ptr_gray[4]);
  assign _0339_ = wr_ptr_gray[4] ^ rd_ptr_gray_sync[4];
  assign _0340_ = ~(_0296_ & wr_ptr_bin[3]);
  assign _0341_ = ~wr_ptr_bin[3];
  assign _0342_ = _0296_ ^ _0341_;
  assign _0343_ = ~_0342_;
  assign _0344_ = ~(_0297_ & wr_ptr_bin[2]);
  assign _0345_ = _0343_ & ~(_0344_);
  assign _0346_ = _0340_ & ~(_0345_);
  assign _0347_ = _0298_ & wr_ptr_bin[1];
  assign _0348_ = _0298_ ^ wr_ptr_bin[1];
  assign _0349_ = wr_ptr_bin_next[0] & ~(_0299_);
  assign _0350_ = _0348_ & ~(_0349_);
  assign _0351_ = _0350_ | _0347_;
  assign _0352_ = ~wr_ptr_bin[2];
  assign _0353_ = _0297_ ^ _0352_;
  assign _0354_ = _0353_ | _0342_;
  assign _0355_ = _0351_ & ~(_0354_);
  assign _0356_ = _0346_ & ~(_0355_);
  assign _0357_ = ~(_0356_ | _0339_);
  assign _0358_ = _0338_ & ~(_0357_);
  assign _0359_ = _0349_ ^ _0348_;
  assign _0360_ = ~(_0359_ | _0626_[0]);
  assign _0626_[2] = ~(_0353_ ^ _0351_);
  assign _0361_ = _0351_ & ~(_0353_);
  assign _0362_ = _0344_ & ~(_0361_);
  assign _0363_ = _0362_ ^ _0343_;
  assign _0364_ = _0626_[2] & ~(_0363_);
  assign _0365_ = ~(_0364_ & _0360_);
  assign _0626_[4] = _0356_ ^ _0339_;
  assign _0366_ = _0626_[4] | _0358_;
  assign _0367_ = _0366_ | _0365_;
  assign _0368_ = ~(_0367_ | _0358_);
  assign _0369_ = _0626_[0] & ~(_0359_);
  assign _0370_ = _0364_ & ~(_0369_);
  assign _0371_ = _0364_ & ~(_0370_);
  assign _0372_ = _0371_ | _0366_;
  assign _0373_ = _0372_ | _0358_;
  assign _0001_ = _0373_ | _0368_;
  assign _0626_[3] = ~_0363_;
  assign do_read = rd_en & ~(empty);
  assign rd_ptr_bin_next[0] = ~rd_ptr_bin[0];
  assign _0374_ = ~(rd_ptr_bin[1] ^ rd_ptr_bin[0]);
  assign _0375_ = _0374_ ^ rd_ptr_bin_next[0];
  assign \bin2gray$func$../rtl/fifo_async.v:267$20.$result [0] = ~_0375_;
  assign _0376_ = do_read ? \bin2gray$func$../rtl/fifo_async.v:267$20.$result [0] : rd_ptr_gray[0];
  assign _0377_ = ~(_0376_ ^ wr_ptr_gray_sync[0]);
  assign rd_ptr_bin_next[1] = ~_0374_;
  assign _0378_ = rd_ptr_bin[1] & rd_ptr_bin[0];
  assign _0379_ = _0378_ ^ _0319_;
  assign _0380_ = _0379_ ^ rd_ptr_bin_next[1];
  assign \bin2gray$func$../rtl/fifo_async.v:267$20.$result [1] = ~_0380_;
  assign _0381_ = do_read ? \bin2gray$func$../rtl/fifo_async.v:267$20.$result [1] : rd_ptr_gray[1];
  assign _0382_ = _0381_ ^ wr_ptr_gray_sync[1];
  assign _0383_ = _0377_ & ~(_0382_);
  assign rd_ptr_bin_next[2] = ~_0379_;
  assign _0384_ = _0378_ & ~(_0319_);
  assign _0385_ = _0384_ ^ _0310_;
  assign _0386_ = _0385_ ^ rd_ptr_bin_next[2];
  assign \bin2gray$func$../rtl/fifo_async.v:267$20.$result [2] = ~_0386_;
  assign _0387_ = do_read ? \bin2gray$func$../rtl/fifo_async.v:267$20.$result [2] : rd_ptr_gray[2];
  assign _0388_ = _0387_ ^ wr_ptr_gray_sync[2];
  assign _0389_ = ~rd_ptr_gray[4];
  assign _0390_ = ~(rd_ptr_bin[3] & rd_ptr_bin[2]);
  assign _0391_ = _0378_ & ~(_0390_);
  assign _0392_ = _0391_ ^ _0389_;
  assign _0393_ = ~(_0392_ ^ _0385_);
  assign \bin2gray$func$../rtl/fifo_async.v:267$20.$result [3] = ~_0393_;
  assign _0394_ = do_read ? \bin2gray$func$../rtl/fifo_async.v:267$20.$result [3] : rd_ptr_gray[3];
  assign _0395_ = _0394_ ^ wr_ptr_gray_sync[3];
  assign _0396_ = _0395_ | _0388_;
  assign _0397_ = _0383_ & ~(_0396_);
  assign _0398_ = do_read ? _0392_ : _0389_;
  assign _0399_ = ~(_0398_ ^ wr_ptr_gray_sync[4]);
  assign _0002_ = _0397_ & ~(_0399_);
  assign _0004_ = wr_en & full;
  assign _0005_ = rd_en & empty;
  assign do_write = wr_en & ~(full);
  assign _0400_ = ~(rd_ptr_gray_sync[3] ^ wr_ptr_gray[3]);
  assign _0401_ = _0339_ & ~(_0400_);
  assign _0402_ = rd_ptr_gray_sync[0] ^ wr_ptr_gray[0];
  assign _0403_ = rd_ptr_gray_sync[1] ^ wr_ptr_gray[1];
  assign _0404_ = _0403_ | _0402_;
  assign _0405_ = rd_ptr_gray_sync[2] ^ wr_ptr_gray[2];
  assign _0406_ = _0405_ | _0404_;
  assign _0407_ = _0401_ & ~(_0406_);
  assign _0408_ = wr_ptr_bin[3] & wr_ptr_bin[2];
  assign _0409_ = wr_ptr_bin[1] & wr_ptr_bin[0];
  assign _0410_ = _0409_ & _0408_;
  assign _0411_ = ~(_0410_ ^ wr_ptr_gray[4]);
  assign _0412_ = ~(_0411_ ^ rd_ptr_gray_sync[4]);
  assign _0413_ = _0409_ & ~(_0352_);
  assign _0414_ = _0413_ ^ _0341_;
  assign _0415_ = ~(_0414_ ^ _0411_);
  assign _0416_ = _0415_ ^ rd_ptr_gray_sync[3];
  assign _0417_ = _0412_ & ~(_0416_);
  assign _0418_ = wr_ptr_bin[1] | ~(wr_ptr_bin[0]);
  assign _0419_ = wr_ptr_bin[0] | ~(wr_ptr_bin[1]);
  assign _0420_ = _0419_ & _0418_;
  assign _0421_ = _0420_ ^ wr_ptr_bin_next[0];
  assign _0422_ = ~(_0421_ ^ rd_ptr_gray_sync[0]);
  assign _0423_ = _0409_ ^ _0352_;
  assign _0424_ = ~(_0423_ ^ _0420_);
  assign _0425_ = ~(_0424_ ^ rd_ptr_gray_sync[1]);
  assign _0426_ = _0425_ | _0422_;
  assign wr_ptr_bin_next[2] = ~_0423_;
  assign _0427_ = wr_ptr_bin_next[2] ^ _0414_;
  assign _0428_ = ~(_0427_ ^ rd_ptr_gray_sync[2]);
  assign _0429_ = _0428_ | _0426_;
  assign _0430_ = _0417_ & ~(_0429_);
  assign _0003_ = do_write ? _0430_ : _0407_;
  assign _0431_ = rd_ptr_bin[0] ? \mem[1] [0] : \mem[0] [0];
  assign _0432_ = rd_ptr_bin[0] ? \mem[3] [0] : \mem[2] [0];
  assign _0433_ = rd_ptr_bin[1] ? _0432_ : _0431_;
  assign _0434_ = rd_ptr_bin[0] ? \mem[5] [0] : \mem[4] [0];
  assign _0435_ = rd_ptr_bin[0] ? \mem[7] [0] : \mem[6] [0];
  assign _0436_ = rd_ptr_bin[1] ? _0435_ : _0434_;
  assign _0437_ = rd_ptr_bin[2] ? _0436_ : _0433_;
  assign _0438_ = rd_ptr_bin[0] ? \mem[9] [0] : \mem[8] [0];
  assign _0439_ = rd_ptr_bin[0] ? \mem[11] [0] : \mem[10] [0];
  assign _0440_ = rd_ptr_bin[1] ? _0439_ : _0438_;
  assign _0441_ = rd_ptr_bin[0] ? \mem[13] [0] : \mem[12] [0];
  assign _0442_ = rd_ptr_bin[0] ? \mem[15] [0] : \mem[14] [0];
  assign _0443_ = rd_ptr_bin[1] ? _0442_ : _0441_;
  assign _0444_ = rd_ptr_bin[2] ? _0443_ : _0440_;
  assign _0006_[0] = rd_ptr_bin[3] ? _0444_ : _0437_;
  assign _0445_ = rd_ptr_bin[0] ? \mem[1] [1] : \mem[0] [1];
  assign _0446_ = rd_ptr_bin[0] ? \mem[3] [1] : \mem[2] [1];
  assign _0447_ = rd_ptr_bin[1] ? _0446_ : _0445_;
  assign _0448_ = rd_ptr_bin[0] ? \mem[5] [1] : \mem[4] [1];
  assign _0449_ = rd_ptr_bin[0] ? \mem[7] [1] : \mem[6] [1];
  assign _0450_ = rd_ptr_bin[1] ? _0449_ : _0448_;
  assign _0451_ = rd_ptr_bin[2] ? _0450_ : _0447_;
  assign _0452_ = rd_ptr_bin[0] ? \mem[9] [1] : \mem[8] [1];
  assign _0453_ = rd_ptr_bin[0] ? \mem[11] [1] : \mem[10] [1];
  assign _0454_ = rd_ptr_bin[1] ? _0453_ : _0452_;
  assign _0455_ = rd_ptr_bin[0] ? \mem[13] [1] : \mem[12] [1];
  assign _0456_ = rd_ptr_bin[0] ? \mem[15] [1] : \mem[14] [1];
  assign _0457_ = rd_ptr_bin[1] ? _0456_ : _0455_;
  assign _0458_ = rd_ptr_bin[2] ? _0457_ : _0454_;
  assign _0006_[1] = rd_ptr_bin[3] ? _0458_ : _0451_;
  assign _0459_ = rd_ptr_bin[0] ? \mem[1] [2] : \mem[0] [2];
  assign _0460_ = rd_ptr_bin[0] ? \mem[3] [2] : \mem[2] [2];
  assign _0461_ = rd_ptr_bin[1] ? _0460_ : _0459_;
  assign _0462_ = rd_ptr_bin[0] ? \mem[5] [2] : \mem[4] [2];
  assign _0463_ = rd_ptr_bin[0] ? \mem[7] [2] : \mem[6] [2];
  assign _0464_ = rd_ptr_bin[1] ? _0463_ : _0462_;
  assign _0465_ = rd_ptr_bin[2] ? _0464_ : _0461_;
  assign _0466_ = rd_ptr_bin[0] ? \mem[9] [2] : \mem[8] [2];
  assign _0467_ = rd_ptr_bin[0] ? \mem[11] [2] : \mem[10] [2];
  assign _0468_ = rd_ptr_bin[1] ? _0467_ : _0466_;
  assign _0469_ = rd_ptr_bin[0] ? \mem[13] [2] : \mem[12] [2];
  assign _0470_ = rd_ptr_bin[0] ? \mem[15] [2] : \mem[14] [2];
  assign _0471_ = rd_ptr_bin[1] ? _0470_ : _0469_;
  assign _0472_ = rd_ptr_bin[2] ? _0471_ : _0468_;
  assign _0006_[2] = rd_ptr_bin[3] ? _0472_ : _0465_;
  assign _0473_ = rd_ptr_bin[0] ? \mem[1] [3] : \mem[0] [3];
  assign _0474_ = rd_ptr_bin[0] ? \mem[3] [3] : \mem[2] [3];
  assign _0475_ = rd_ptr_bin[1] ? _0474_ : _0473_;
  assign _0476_ = rd_ptr_bin[0] ? \mem[5] [3] : \mem[4] [3];
  assign _0477_ = rd_ptr_bin[0] ? \mem[7] [3] : \mem[6] [3];
  assign _0478_ = rd_ptr_bin[1] ? _0477_ : _0476_;
  assign _0479_ = rd_ptr_bin[2] ? _0478_ : _0475_;
  assign _0480_ = rd_ptr_bin[0] ? \mem[9] [3] : \mem[8] [3];
  assign _0481_ = rd_ptr_bin[0] ? \mem[11] [3] : \mem[10] [3];
  assign _0482_ = rd_ptr_bin[1] ? _0481_ : _0480_;
  assign _0483_ = rd_ptr_bin[0] ? \mem[13] [3] : \mem[12] [3];
  assign _0484_ = rd_ptr_bin[0] ? \mem[15] [3] : \mem[14] [3];
  assign _0485_ = rd_ptr_bin[1] ? _0484_ : _0483_;
  assign _0486_ = rd_ptr_bin[2] ? _0485_ : _0482_;
  assign _0006_[3] = rd_ptr_bin[3] ? _0486_ : _0479_;
  assign _0487_ = rd_ptr_bin[0] ? \mem[1] [4] : \mem[0] [4];
  assign _0488_ = rd_ptr_bin[0] ? \mem[3] [4] : \mem[2] [4];
  assign _0489_ = rd_ptr_bin[1] ? _0488_ : _0487_;
  assign _0490_ = rd_ptr_bin[0] ? \mem[5] [4] : \mem[4] [4];
  assign _0491_ = rd_ptr_bin[0] ? \mem[7] [4] : \mem[6] [4];
  assign _0492_ = rd_ptr_bin[1] ? _0491_ : _0490_;
  assign _0493_ = rd_ptr_bin[2] ? _0492_ : _0489_;
  assign _0494_ = rd_ptr_bin[0] ? \mem[9] [4] : \mem[8] [4];
  assign _0495_ = rd_ptr_bin[0] ? \mem[11] [4] : \mem[10] [4];
  assign _0496_ = rd_ptr_bin[1] ? _0495_ : _0494_;
  assign _0497_ = rd_ptr_bin[0] ? \mem[13] [4] : \mem[12] [4];
  assign _0498_ = rd_ptr_bin[0] ? \mem[15] [4] : \mem[14] [4];
  assign _0499_ = rd_ptr_bin[1] ? _0498_ : _0497_;
  assign _0500_ = rd_ptr_bin[2] ? _0499_ : _0496_;
  assign _0006_[4] = rd_ptr_bin[3] ? _0500_ : _0493_;
  assign _0501_ = rd_ptr_bin[0] ? \mem[1] [5] : \mem[0] [5];
  assign _0502_ = rd_ptr_bin[0] ? \mem[3] [5] : \mem[2] [5];
  assign _0503_ = rd_ptr_bin[1] ? _0502_ : _0501_;
  assign _0504_ = rd_ptr_bin[0] ? \mem[5] [5] : \mem[4] [5];
  assign _0505_ = rd_ptr_bin[0] ? \mem[7] [5] : \mem[6] [5];
  assign _0506_ = rd_ptr_bin[1] ? _0505_ : _0504_;
  assign _0507_ = rd_ptr_bin[2] ? _0506_ : _0503_;
  assign _0508_ = rd_ptr_bin[0] ? \mem[9] [5] : \mem[8] [5];
  assign _0509_ = rd_ptr_bin[0] ? \mem[11] [5] : \mem[10] [5];
  assign _0510_ = rd_ptr_bin[1] ? _0509_ : _0508_;
  assign _0511_ = rd_ptr_bin[0] ? \mem[13] [5] : \mem[12] [5];
  assign _0512_ = rd_ptr_bin[0] ? \mem[15] [5] : \mem[14] [5];
  assign _0513_ = rd_ptr_bin[1] ? _0512_ : _0511_;
  assign _0514_ = rd_ptr_bin[2] ? _0513_ : _0510_;
  assign _0006_[5] = rd_ptr_bin[3] ? _0514_ : _0507_;
  assign _0515_ = rd_ptr_bin[0] ? \mem[1] [6] : \mem[0] [6];
  assign _0516_ = rd_ptr_bin[0] ? \mem[3] [6] : \mem[2] [6];
  assign _0517_ = rd_ptr_bin[1] ? _0516_ : _0515_;
  assign _0518_ = rd_ptr_bin[0] ? \mem[5] [6] : \mem[4] [6];
  assign _0519_ = rd_ptr_bin[0] ? \mem[7] [6] : \mem[6] [6];
  assign _0520_ = rd_ptr_bin[1] ? _0519_ : _0518_;
  assign _0521_ = rd_ptr_bin[2] ? _0520_ : _0517_;
  assign _0522_ = rd_ptr_bin[0] ? \mem[9] [6] : \mem[8] [6];
  assign _0523_ = rd_ptr_bin[0] ? \mem[11] [6] : \mem[10] [6];
  assign _0524_ = rd_ptr_bin[1] ? _0523_ : _0522_;
  assign _0525_ = rd_ptr_bin[0] ? \mem[13] [6] : \mem[12] [6];
  assign _0526_ = rd_ptr_bin[0] ? \mem[15] [6] : \mem[14] [6];
  assign _0527_ = rd_ptr_bin[1] ? _0526_ : _0525_;
  assign _0528_ = rd_ptr_bin[2] ? _0527_ : _0524_;
  assign _0006_[6] = rd_ptr_bin[3] ? _0528_ : _0521_;
  assign _0529_ = rd_ptr_bin[0] ? \mem[1] [7] : \mem[0] [7];
  assign _0530_ = rd_ptr_bin[0] ? \mem[3] [7] : \mem[2] [7];
  assign _0531_ = rd_ptr_bin[1] ? _0530_ : _0529_;
  assign _0532_ = rd_ptr_bin[0] ? \mem[5] [7] : \mem[4] [7];
  assign _0533_ = rd_ptr_bin[0] ? \mem[7] [7] : \mem[6] [7];
  assign _0534_ = rd_ptr_bin[1] ? _0533_ : _0532_;
  assign _0535_ = rd_ptr_bin[2] ? _0534_ : _0531_;
  assign _0536_ = rd_ptr_bin[0] ? \mem[9] [7] : \mem[8] [7];
  assign _0537_ = rd_ptr_bin[0] ? \mem[11] [7] : \mem[10] [7];
  assign _0538_ = rd_ptr_bin[1] ? _0537_ : _0536_;
  assign _0539_ = rd_ptr_bin[0] ? \mem[13] [7] : \mem[12] [7];
  assign _0540_ = rd_ptr_bin[0] ? \mem[15] [7] : \mem[14] [7];
  assign _0541_ = rd_ptr_bin[1] ? _0540_ : _0539_;
  assign _0542_ = rd_ptr_bin[2] ? _0541_ : _0538_;
  assign _0006_[7] = rd_ptr_bin[3] ? _0542_ : _0535_;
  assign _0543_ = rd_ptr_bin[0] ? \mem[1] [8] : \mem[0] [8];
  assign _0544_ = rd_ptr_bin[0] ? \mem[3] [8] : \mem[2] [8];
  assign _0545_ = rd_ptr_bin[1] ? _0544_ : _0543_;
  assign _0546_ = rd_ptr_bin[0] ? \mem[5] [8] : \mem[4] [8];
  assign _0547_ = rd_ptr_bin[0] ? \mem[7] [8] : \mem[6] [8];
  assign _0548_ = rd_ptr_bin[1] ? _0547_ : _0546_;
  assign _0549_ = rd_ptr_bin[2] ? _0548_ : _0545_;
  assign _0550_ = rd_ptr_bin[0] ? \mem[9] [8] : \mem[8] [8];
  assign _0551_ = rd_ptr_bin[0] ? \mem[11] [8] : \mem[10] [8];
  assign _0552_ = rd_ptr_bin[1] ? _0551_ : _0550_;
  assign _0553_ = rd_ptr_bin[0] ? \mem[13] [8] : \mem[12] [8];
  assign _0554_ = rd_ptr_bin[0] ? \mem[15] [8] : \mem[14] [8];
  assign _0555_ = rd_ptr_bin[1] ? _0554_ : _0553_;
  assign _0556_ = rd_ptr_bin[2] ? _0555_ : _0552_;
  assign _0006_[8] = rd_ptr_bin[3] ? _0556_ : _0549_;
  assign _0557_ = rd_ptr_bin[0] ? \mem[1] [9] : \mem[0] [9];
  assign _0558_ = rd_ptr_bin[0] ? \mem[3] [9] : \mem[2] [9];
  assign _0559_ = rd_ptr_bin[1] ? _0558_ : _0557_;
  assign _0560_ = rd_ptr_bin[0] ? \mem[5] [9] : \mem[4] [9];
  assign _0561_ = rd_ptr_bin[0] ? \mem[7] [9] : \mem[6] [9];
  assign _0562_ = rd_ptr_bin[1] ? _0561_ : _0560_;
  assign _0563_ = rd_ptr_bin[2] ? _0562_ : _0559_;
  assign _0564_ = rd_ptr_bin[0] ? \mem[9] [9] : \mem[8] [9];
  assign _0565_ = rd_ptr_bin[0] ? \mem[11] [9] : \mem[10] [9];
  assign _0566_ = rd_ptr_bin[1] ? _0565_ : _0564_;
  assign _0567_ = rd_ptr_bin[0] ? \mem[13] [9] : \mem[12] [9];
  assign _0568_ = rd_ptr_bin[0] ? \mem[15] [9] : \mem[14] [9];
  assign _0569_ = rd_ptr_bin[1] ? _0568_ : _0567_;
  assign _0570_ = rd_ptr_bin[2] ? _0569_ : _0566_;
  assign _0006_[9] = rd_ptr_bin[3] ? _0570_ : _0563_;
  assign _0571_ = rd_ptr_bin[0] ? \mem[1] [10] : \mem[0] [10];
  assign _0572_ = rd_ptr_bin[0] ? \mem[3] [10] : \mem[2] [10];
  assign _0573_ = rd_ptr_bin[1] ? _0572_ : _0571_;
  assign _0574_ = rd_ptr_bin[0] ? \mem[5] [10] : \mem[4] [10];
  assign _0575_ = rd_ptr_bin[0] ? \mem[7] [10] : \mem[6] [10];
  assign _0576_ = rd_ptr_bin[1] ? _0575_ : _0574_;
  assign _0577_ = rd_ptr_bin[2] ? _0576_ : _0573_;
  assign _0578_ = rd_ptr_bin[0] ? \mem[9] [10] : \mem[8] [10];
  assign _0579_ = rd_ptr_bin[0] ? \mem[11] [10] : \mem[10] [10];
  assign _0580_ = rd_ptr_bin[1] ? _0579_ : _0578_;
  assign _0581_ = rd_ptr_bin[0] ? \mem[13] [10] : \mem[12] [10];
  assign _0582_ = rd_ptr_bin[0] ? \mem[15] [10] : \mem[14] [10];
  assign _0583_ = rd_ptr_bin[1] ? _0582_ : _0581_;
  assign _0584_ = rd_ptr_bin[2] ? _0583_ : _0580_;
  assign _0006_[10] = rd_ptr_bin[3] ? _0584_ : _0577_;
  assign _0585_ = rd_ptr_bin[0] ? \mem[1] [11] : \mem[0] [11];
  assign _0586_ = rd_ptr_bin[0] ? \mem[3] [11] : \mem[2] [11];
  assign _0587_ = rd_ptr_bin[1] ? _0586_ : _0585_;
  assign _0588_ = rd_ptr_bin[0] ? \mem[5] [11] : \mem[4] [11];
  assign _0589_ = rd_ptr_bin[0] ? \mem[7] [11] : \mem[6] [11];
  assign _0590_ = rd_ptr_bin[1] ? _0589_ : _0588_;
  assign _0591_ = rd_ptr_bin[2] ? _0590_ : _0587_;
  assign _0592_ = rd_ptr_bin[0] ? \mem[9] [11] : \mem[8] [11];
  assign _0593_ = rd_ptr_bin[0] ? \mem[11] [11] : \mem[10] [11];
  assign _0594_ = rd_ptr_bin[1] ? _0593_ : _0592_;
  assign _0595_ = rd_ptr_bin[0] ? \mem[13] [11] : \mem[12] [11];
  assign _0596_ = rd_ptr_bin[0] ? \mem[15] [11] : \mem[14] [11];
  assign _0597_ = rd_ptr_bin[1] ? _0596_ : _0595_;
  assign _0598_ = rd_ptr_bin[2] ? _0597_ : _0594_;
  assign _0006_[11] = rd_ptr_bin[3] ? _0598_ : _0591_;
  assign _0599_ = rd_ptr_bin[0] ? \mem[1] [12] : \mem[0] [12];
  assign _0600_ = rd_ptr_bin[0] ? \mem[3] [12] : \mem[2] [12];
  assign _0601_ = rd_ptr_bin[1] ? _0600_ : _0599_;
  assign _0602_ = rd_ptr_bin[0] ? \mem[5] [12] : \mem[4] [12];
  assign _0603_ = rd_ptr_bin[0] ? \mem[7] [12] : \mem[6] [12];
  assign _0604_ = rd_ptr_bin[1] ? _0603_ : _0602_;
  assign _0605_ = rd_ptr_bin[2] ? _0604_ : _0601_;
  assign _0606_ = rd_ptr_bin[0] ? \mem[9] [12] : \mem[8] [12];
  assign _0607_ = rd_ptr_bin[0] ? \mem[11] [12] : \mem[10] [12];
  assign _0608_ = rd_ptr_bin[1] ? _0607_ : _0606_;
  assign _0609_ = rd_ptr_bin[0] ? \mem[13] [12] : \mem[12] [12];
  assign _0610_ = rd_ptr_bin[0] ? \mem[15] [12] : \mem[14] [12];
  assign _0611_ = rd_ptr_bin[1] ? _0610_ : _0609_;
  assign _0612_ = rd_ptr_bin[2] ? _0611_ : _0608_;
  assign _0006_[12] = rd_ptr_bin[3] ? _0612_ : _0605_;
  assign _0613_ = rd_ptr_bin[0] ? \mem[1] [13] : \mem[0] [13];
  assign _0614_ = rd_ptr_bin[0] ? \mem[3] [13] : \mem[2] [13];
  assign _0615_ = rd_ptr_bin[1] ? _0614_ : _0613_;
  assign _0616_ = rd_ptr_bin[0] ? \mem[5] [13] : \mem[4] [13];
  assign _0617_ = rd_ptr_bin[0] ? \mem[7] [13] : \mem[6] [13];
  assign _0618_ = rd_ptr_bin[1] ? _0617_ : _0616_;
  assign _0619_ = rd_ptr_bin[2] ? _0618_ : _0615_;
  assign _0620_ = rd_ptr_bin[0] ? \mem[9] [13] : \mem[8] [13];
  assign _0621_ = rd_ptr_bin[0] ? \mem[11] [13] : \mem[10] [13];
  assign _0622_ = rd_ptr_bin[1] ? _0621_ : _0620_;
  assign _0623_ = rd_ptr_bin[0] ? \mem[13] [13] : \mem[12] [13];
  assign _0624_ = rd_ptr_bin[0] ? \mem[15] [13] : \mem[14] [13];
  assign _0023_ = rd_ptr_bin[1] ? _0624_ : _0623_;
  assign _0024_ = rd_ptr_bin[2] ? _0023_ : _0622_;
  assign _0006_[13] = rd_ptr_bin[3] ? _0024_ : _0619_;
  assign _0025_ = rd_ptr_bin[0] ? \mem[1] [14] : \mem[0] [14];
  assign _0026_ = rd_ptr_bin[0] ? \mem[3] [14] : \mem[2] [14];
  assign _0027_ = rd_ptr_bin[1] ? _0026_ : _0025_;
  assign _0028_ = rd_ptr_bin[0] ? \mem[5] [14] : \mem[4] [14];
  assign _0029_ = rd_ptr_bin[0] ? \mem[7] [14] : \mem[6] [14];
  assign _0030_ = rd_ptr_bin[1] ? _0029_ : _0028_;
  assign _0031_ = rd_ptr_bin[2] ? _0030_ : _0027_;
  assign _0032_ = rd_ptr_bin[0] ? \mem[9] [14] : \mem[8] [14];
  assign _0033_ = rd_ptr_bin[0] ? \mem[11] [14] : \mem[10] [14];
  assign _0034_ = rd_ptr_bin[1] ? _0033_ : _0032_;
  assign _0035_ = rd_ptr_bin[0] ? \mem[13] [14] : \mem[12] [14];
  assign _0036_ = rd_ptr_bin[0] ? \mem[15] [14] : \mem[14] [14];
  assign _0037_ = rd_ptr_bin[1] ? _0036_ : _0035_;
  assign _0038_ = rd_ptr_bin[2] ? _0037_ : _0034_;
  assign _0006_[14] = rd_ptr_bin[3] ? _0038_ : _0031_;
  assign _0039_ = rd_ptr_bin[0] ? \mem[1] [15] : \mem[0] [15];
  assign _0040_ = rd_ptr_bin[0] ? \mem[3] [15] : \mem[2] [15];
  assign _0041_ = rd_ptr_bin[1] ? _0040_ : _0039_;
  assign _0042_ = rd_ptr_bin[0] ? \mem[5] [15] : \mem[4] [15];
  assign _0043_ = rd_ptr_bin[0] ? \mem[7] [15] : \mem[6] [15];
  assign _0044_ = rd_ptr_bin[1] ? _0043_ : _0042_;
  assign _0045_ = rd_ptr_bin[2] ? _0044_ : _0041_;
  assign _0046_ = rd_ptr_bin[0] ? \mem[9] [15] : \mem[8] [15];
  assign _0047_ = rd_ptr_bin[0] ? \mem[11] [15] : \mem[10] [15];
  assign _0048_ = rd_ptr_bin[1] ? _0047_ : _0046_;
  assign _0049_ = rd_ptr_bin[0] ? \mem[13] [15] : \mem[12] [15];
  assign _0050_ = rd_ptr_bin[0] ? \mem[15] [15] : \mem[14] [15];
  assign _0051_ = rd_ptr_bin[1] ? _0050_ : _0049_;
  assign _0052_ = rd_ptr_bin[2] ? _0051_ : _0048_;
  assign _0006_[15] = rd_ptr_bin[3] ? _0052_ : _0045_;
  assign _0053_ = rd_ptr_bin[0] ? \mem[1] [16] : \mem[0] [16];
  assign _0054_ = rd_ptr_bin[0] ? \mem[3] [16] : \mem[2] [16];
  assign _0055_ = rd_ptr_bin[1] ? _0054_ : _0053_;
  assign _0056_ = rd_ptr_bin[0] ? \mem[5] [16] : \mem[4] [16];
  assign _0057_ = rd_ptr_bin[0] ? \mem[7] [16] : \mem[6] [16];
  assign _0058_ = rd_ptr_bin[1] ? _0057_ : _0056_;
  assign _0059_ = rd_ptr_bin[2] ? _0058_ : _0055_;
  assign _0060_ = rd_ptr_bin[0] ? \mem[9] [16] : \mem[8] [16];
  assign _0061_ = rd_ptr_bin[0] ? \mem[11] [16] : \mem[10] [16];
  assign _0062_ = rd_ptr_bin[1] ? _0061_ : _0060_;
  assign _0063_ = rd_ptr_bin[0] ? \mem[13] [16] : \mem[12] [16];
  assign _0064_ = rd_ptr_bin[0] ? \mem[15] [16] : \mem[14] [16];
  assign _0065_ = rd_ptr_bin[1] ? _0064_ : _0063_;
  assign _0066_ = rd_ptr_bin[2] ? _0065_ : _0062_;
  assign _0006_[16] = rd_ptr_bin[3] ? _0066_ : _0059_;
  assign _0067_ = rd_ptr_bin[0] ? \mem[1] [17] : \mem[0] [17];
  assign _0068_ = rd_ptr_bin[0] ? \mem[3] [17] : \mem[2] [17];
  assign _0069_ = rd_ptr_bin[1] ? _0068_ : _0067_;
  assign _0070_ = rd_ptr_bin[0] ? \mem[5] [17] : \mem[4] [17];
  assign _0071_ = rd_ptr_bin[0] ? \mem[7] [17] : \mem[6] [17];
  assign _0072_ = rd_ptr_bin[1] ? _0071_ : _0070_;
  assign _0073_ = rd_ptr_bin[2] ? _0072_ : _0069_;
  assign _0074_ = rd_ptr_bin[0] ? \mem[9] [17] : \mem[8] [17];
  assign _0075_ = rd_ptr_bin[0] ? \mem[11] [17] : \mem[10] [17];
  assign _0076_ = rd_ptr_bin[1] ? _0075_ : _0074_;
  assign _0077_ = rd_ptr_bin[0] ? \mem[13] [17] : \mem[12] [17];
  assign _0078_ = rd_ptr_bin[0] ? \mem[15] [17] : \mem[14] [17];
  assign _0079_ = rd_ptr_bin[1] ? _0078_ : _0077_;
  assign _0080_ = rd_ptr_bin[2] ? _0079_ : _0076_;
  assign _0006_[17] = rd_ptr_bin[3] ? _0080_ : _0073_;
  assign _0081_ = rd_ptr_bin[0] ? \mem[1] [18] : \mem[0] [18];
  assign _0082_ = rd_ptr_bin[0] ? \mem[3] [18] : \mem[2] [18];
  assign _0083_ = rd_ptr_bin[1] ? _0082_ : _0081_;
  assign _0084_ = rd_ptr_bin[0] ? \mem[5] [18] : \mem[4] [18];
  assign _0085_ = rd_ptr_bin[0] ? \mem[7] [18] : \mem[6] [18];
  assign _0086_ = rd_ptr_bin[1] ? _0085_ : _0084_;
  assign _0087_ = rd_ptr_bin[2] ? _0086_ : _0083_;
  assign _0088_ = rd_ptr_bin[0] ? \mem[9] [18] : \mem[8] [18];
  assign _0089_ = rd_ptr_bin[0] ? \mem[11] [18] : \mem[10] [18];
  assign _0090_ = rd_ptr_bin[1] ? _0089_ : _0088_;
  assign _0091_ = rd_ptr_bin[0] ? \mem[13] [18] : \mem[12] [18];
  assign _0092_ = rd_ptr_bin[0] ? \mem[15] [18] : \mem[14] [18];
  assign _0093_ = rd_ptr_bin[1] ? _0092_ : _0091_;
  assign _0094_ = rd_ptr_bin[2] ? _0093_ : _0090_;
  assign _0006_[18] = rd_ptr_bin[3] ? _0094_ : _0087_;
  assign _0095_ = rd_ptr_bin[0] ? \mem[1] [19] : \mem[0] [19];
  assign _0096_ = rd_ptr_bin[0] ? \mem[3] [19] : \mem[2] [19];
  assign _0097_ = rd_ptr_bin[1] ? _0096_ : _0095_;
  assign _0098_ = rd_ptr_bin[0] ? \mem[5] [19] : \mem[4] [19];
  assign _0099_ = rd_ptr_bin[0] ? \mem[7] [19] : \mem[6] [19];
  assign _0100_ = rd_ptr_bin[1] ? _0099_ : _0098_;
  assign _0101_ = rd_ptr_bin[2] ? _0100_ : _0097_;
  assign _0102_ = rd_ptr_bin[0] ? \mem[9] [19] : \mem[8] [19];
  assign _0103_ = rd_ptr_bin[0] ? \mem[11] [19] : \mem[10] [19];
  assign _0104_ = rd_ptr_bin[1] ? _0103_ : _0102_;
  assign _0105_ = rd_ptr_bin[0] ? \mem[13] [19] : \mem[12] [19];
  assign _0106_ = rd_ptr_bin[0] ? \mem[15] [19] : \mem[14] [19];
  assign _0107_ = rd_ptr_bin[1] ? _0106_ : _0105_;
  assign _0108_ = rd_ptr_bin[2] ? _0107_ : _0104_;
  assign _0006_[19] = rd_ptr_bin[3] ? _0108_ : _0101_;
  assign _0109_ = rd_ptr_bin[0] ? \mem[1] [20] : \mem[0] [20];
  assign _0110_ = rd_ptr_bin[0] ? \mem[3] [20] : \mem[2] [20];
  assign _0111_ = rd_ptr_bin[1] ? _0110_ : _0109_;
  assign _0112_ = rd_ptr_bin[0] ? \mem[5] [20] : \mem[4] [20];
  assign _0113_ = rd_ptr_bin[0] ? \mem[7] [20] : \mem[6] [20];
  assign _0114_ = rd_ptr_bin[1] ? _0113_ : _0112_;
  assign _0115_ = rd_ptr_bin[2] ? _0114_ : _0111_;
  assign _0116_ = rd_ptr_bin[0] ? \mem[9] [20] : \mem[8] [20];
  assign _0117_ = rd_ptr_bin[0] ? \mem[11] [20] : \mem[10] [20];
  assign _0118_ = rd_ptr_bin[1] ? _0117_ : _0116_;
  assign _0119_ = rd_ptr_bin[0] ? \mem[13] [20] : \mem[12] [20];
  assign _0120_ = rd_ptr_bin[0] ? \mem[15] [20] : \mem[14] [20];
  assign _0121_ = rd_ptr_bin[1] ? _0120_ : _0119_;
  assign _0122_ = rd_ptr_bin[2] ? _0121_ : _0118_;
  assign _0006_[20] = rd_ptr_bin[3] ? _0122_ : _0115_;
  assign _0123_ = rd_ptr_bin[0] ? \mem[1] [21] : \mem[0] [21];
  assign _0124_ = rd_ptr_bin[0] ? \mem[3] [21] : \mem[2] [21];
  assign _0125_ = rd_ptr_bin[1] ? _0124_ : _0123_;
  assign _0126_ = rd_ptr_bin[0] ? \mem[5] [21] : \mem[4] [21];
  assign _0127_ = rd_ptr_bin[0] ? \mem[7] [21] : \mem[6] [21];
  assign _0128_ = rd_ptr_bin[1] ? _0127_ : _0126_;
  assign _0129_ = rd_ptr_bin[2] ? _0128_ : _0125_;
  assign _0130_ = rd_ptr_bin[0] ? \mem[9] [21] : \mem[8] [21];
  assign _0131_ = rd_ptr_bin[0] ? \mem[11] [21] : \mem[10] [21];
  assign _0132_ = rd_ptr_bin[1] ? _0131_ : _0130_;
  assign _0133_ = rd_ptr_bin[0] ? \mem[13] [21] : \mem[12] [21];
  assign _0134_ = rd_ptr_bin[0] ? \mem[15] [21] : \mem[14] [21];
  assign _0135_ = rd_ptr_bin[1] ? _0134_ : _0133_;
  assign _0136_ = rd_ptr_bin[2] ? _0135_ : _0132_;
  assign _0006_[21] = rd_ptr_bin[3] ? _0136_ : _0129_;
  assign _0137_ = rd_ptr_bin[0] ? \mem[1] [22] : \mem[0] [22];
  assign _0138_ = rd_ptr_bin[0] ? \mem[3] [22] : \mem[2] [22];
  assign _0139_ = rd_ptr_bin[1] ? _0138_ : _0137_;
  assign _0140_ = rd_ptr_bin[0] ? \mem[5] [22] : \mem[4] [22];
  assign _0141_ = rd_ptr_bin[0] ? \mem[7] [22] : \mem[6] [22];
  assign _0142_ = rd_ptr_bin[1] ? _0141_ : _0140_;
  assign _0143_ = rd_ptr_bin[2] ? _0142_ : _0139_;
  assign _0144_ = rd_ptr_bin[0] ? \mem[9] [22] : \mem[8] [22];
  assign _0145_ = rd_ptr_bin[0] ? \mem[11] [22] : \mem[10] [22];
  assign _0146_ = rd_ptr_bin[1] ? _0145_ : _0144_;
  assign _0147_ = rd_ptr_bin[0] ? \mem[13] [22] : \mem[12] [22];
  assign _0148_ = rd_ptr_bin[0] ? \mem[15] [22] : \mem[14] [22];
  assign _0149_ = rd_ptr_bin[1] ? _0148_ : _0147_;
  assign _0150_ = rd_ptr_bin[2] ? _0149_ : _0146_;
  assign _0006_[22] = rd_ptr_bin[3] ? _0150_ : _0143_;
  assign _0151_ = rd_ptr_bin[0] ? \mem[1] [23] : \mem[0] [23];
  assign _0152_ = rd_ptr_bin[0] ? \mem[3] [23] : \mem[2] [23];
  assign _0153_ = rd_ptr_bin[1] ? _0152_ : _0151_;
  assign _0154_ = rd_ptr_bin[0] ? \mem[5] [23] : \mem[4] [23];
  assign _0155_ = rd_ptr_bin[0] ? \mem[7] [23] : \mem[6] [23];
  assign _0156_ = rd_ptr_bin[1] ? _0155_ : _0154_;
  assign _0157_ = rd_ptr_bin[2] ? _0156_ : _0153_;
  assign _0158_ = rd_ptr_bin[0] ? \mem[9] [23] : \mem[8] [23];
  assign _0159_ = rd_ptr_bin[0] ? \mem[11] [23] : \mem[10] [23];
  assign _0160_ = rd_ptr_bin[1] ? _0159_ : _0158_;
  assign _0161_ = rd_ptr_bin[0] ? \mem[13] [23] : \mem[12] [23];
  assign _0162_ = rd_ptr_bin[0] ? \mem[15] [23] : \mem[14] [23];
  assign _0163_ = rd_ptr_bin[1] ? _0162_ : _0161_;
  assign _0164_ = rd_ptr_bin[2] ? _0163_ : _0160_;
  assign _0006_[23] = rd_ptr_bin[3] ? _0164_ : _0157_;
  assign _0165_ = rd_ptr_bin[0] ? \mem[1] [24] : \mem[0] [24];
  assign _0166_ = rd_ptr_bin[0] ? \mem[3] [24] : \mem[2] [24];
  assign _0167_ = rd_ptr_bin[1] ? _0166_ : _0165_;
  assign _0168_ = rd_ptr_bin[0] ? \mem[5] [24] : \mem[4] [24];
  assign _0169_ = rd_ptr_bin[0] ? \mem[7] [24] : \mem[6] [24];
  assign _0170_ = rd_ptr_bin[1] ? _0169_ : _0168_;
  assign _0171_ = rd_ptr_bin[2] ? _0170_ : _0167_;
  assign _0172_ = rd_ptr_bin[0] ? \mem[9] [24] : \mem[8] [24];
  assign _0173_ = rd_ptr_bin[0] ? \mem[11] [24] : \mem[10] [24];
  assign _0174_ = rd_ptr_bin[1] ? _0173_ : _0172_;
  assign _0175_ = rd_ptr_bin[0] ? \mem[13] [24] : \mem[12] [24];
  assign _0176_ = rd_ptr_bin[0] ? \mem[15] [24] : \mem[14] [24];
  assign _0177_ = rd_ptr_bin[1] ? _0176_ : _0175_;
  assign _0178_ = rd_ptr_bin[2] ? _0177_ : _0174_;
  assign _0006_[24] = rd_ptr_bin[3] ? _0178_ : _0171_;
  assign _0179_ = rd_ptr_bin[0] ? \mem[1] [25] : \mem[0] [25];
  assign _0180_ = rd_ptr_bin[0] ? \mem[3] [25] : \mem[2] [25];
  assign _0181_ = rd_ptr_bin[1] ? _0180_ : _0179_;
  assign _0182_ = rd_ptr_bin[0] ? \mem[5] [25] : \mem[4] [25];
  assign _0183_ = rd_ptr_bin[0] ? \mem[7] [25] : \mem[6] [25];
  assign _0184_ = rd_ptr_bin[1] ? _0183_ : _0182_;
  assign _0185_ = rd_ptr_bin[2] ? _0184_ : _0181_;
  assign _0186_ = rd_ptr_bin[0] ? \mem[9] [25] : \mem[8] [25];
  assign _0187_ = rd_ptr_bin[0] ? \mem[11] [25] : \mem[10] [25];
  assign _0188_ = rd_ptr_bin[1] ? _0187_ : _0186_;
  assign _0189_ = rd_ptr_bin[0] ? \mem[13] [25] : \mem[12] [25];
  assign _0190_ = rd_ptr_bin[0] ? \mem[15] [25] : \mem[14] [25];
  assign _0191_ = rd_ptr_bin[1] ? _0190_ : _0189_;
  assign _0192_ = rd_ptr_bin[2] ? _0191_ : _0188_;
  assign _0006_[25] = rd_ptr_bin[3] ? _0192_ : _0185_;
  assign _0193_ = rd_ptr_bin[0] ? \mem[1] [26] : \mem[0] [26];
  assign _0194_ = rd_ptr_bin[0] ? \mem[3] [26] : \mem[2] [26];
  assign _0195_ = rd_ptr_bin[1] ? _0194_ : _0193_;
  assign _0196_ = rd_ptr_bin[0] ? \mem[5] [26] : \mem[4] [26];
  assign _0197_ = rd_ptr_bin[0] ? \mem[7] [26] : \mem[6] [26];
  assign _0198_ = rd_ptr_bin[1] ? _0197_ : _0196_;
  assign _0199_ = rd_ptr_bin[2] ? _0198_ : _0195_;
  assign _0200_ = rd_ptr_bin[0] ? \mem[9] [26] : \mem[8] [26];
  assign _0201_ = rd_ptr_bin[0] ? \mem[11] [26] : \mem[10] [26];
  assign _0202_ = rd_ptr_bin[1] ? _0201_ : _0200_;
  assign _0203_ = rd_ptr_bin[0] ? \mem[13] [26] : \mem[12] [26];
  assign _0204_ = rd_ptr_bin[0] ? \mem[15] [26] : \mem[14] [26];
  assign _0205_ = rd_ptr_bin[1] ? _0204_ : _0203_;
  assign _0206_ = rd_ptr_bin[2] ? _0205_ : _0202_;
  assign _0006_[26] = rd_ptr_bin[3] ? _0206_ : _0199_;
  assign _0207_ = rd_ptr_bin[0] ? \mem[1] [27] : \mem[0] [27];
  assign _0208_ = rd_ptr_bin[0] ? \mem[3] [27] : \mem[2] [27];
  assign _0209_ = rd_ptr_bin[1] ? _0208_ : _0207_;
  assign _0210_ = rd_ptr_bin[0] ? \mem[5] [27] : \mem[4] [27];
  assign _0211_ = rd_ptr_bin[0] ? \mem[7] [27] : \mem[6] [27];
  assign _0212_ = rd_ptr_bin[1] ? _0211_ : _0210_;
  assign _0213_ = rd_ptr_bin[2] ? _0212_ : _0209_;
  assign _0214_ = rd_ptr_bin[0] ? \mem[9] [27] : \mem[8] [27];
  assign _0215_ = rd_ptr_bin[0] ? \mem[11] [27] : \mem[10] [27];
  assign _0216_ = rd_ptr_bin[1] ? _0215_ : _0214_;
  assign _0217_ = rd_ptr_bin[0] ? \mem[13] [27] : \mem[12] [27];
  assign _0218_ = rd_ptr_bin[0] ? \mem[15] [27] : \mem[14] [27];
  assign _0219_ = rd_ptr_bin[1] ? _0218_ : _0217_;
  assign _0220_ = rd_ptr_bin[2] ? _0219_ : _0216_;
  assign _0006_[27] = rd_ptr_bin[3] ? _0220_ : _0213_;
  assign _0221_ = rd_ptr_bin[0] ? \mem[1] [28] : \mem[0] [28];
  assign _0222_ = rd_ptr_bin[0] ? \mem[3] [28] : \mem[2] [28];
  assign _0223_ = rd_ptr_bin[1] ? _0222_ : _0221_;
  assign _0224_ = rd_ptr_bin[0] ? \mem[5] [28] : \mem[4] [28];
  assign _0225_ = rd_ptr_bin[0] ? \mem[7] [28] : \mem[6] [28];
  assign _0226_ = rd_ptr_bin[1] ? _0225_ : _0224_;
  assign _0227_ = rd_ptr_bin[2] ? _0226_ : _0223_;
  assign _0228_ = rd_ptr_bin[0] ? \mem[9] [28] : \mem[8] [28];
  assign _0229_ = rd_ptr_bin[0] ? \mem[11] [28] : \mem[10] [28];
  assign _0230_ = rd_ptr_bin[1] ? _0229_ : _0228_;
  assign _0231_ = rd_ptr_bin[0] ? \mem[13] [28] : \mem[12] [28];
  assign _0232_ = rd_ptr_bin[0] ? \mem[15] [28] : \mem[14] [28];
  assign _0233_ = rd_ptr_bin[1] ? _0232_ : _0231_;
  assign _0234_ = rd_ptr_bin[2] ? _0233_ : _0230_;
  assign _0006_[28] = rd_ptr_bin[3] ? _0234_ : _0227_;
  assign _0235_ = rd_ptr_bin[0] ? \mem[1] [29] : \mem[0] [29];
  assign _0236_ = rd_ptr_bin[0] ? \mem[3] [29] : \mem[2] [29];
  assign _0237_ = rd_ptr_bin[1] ? _0236_ : _0235_;
  assign _0238_ = rd_ptr_bin[0] ? \mem[5] [29] : \mem[4] [29];
  assign _0239_ = rd_ptr_bin[0] ? \mem[7] [29] : \mem[6] [29];
  assign _0240_ = rd_ptr_bin[1] ? _0239_ : _0238_;
  assign _0241_ = rd_ptr_bin[2] ? _0240_ : _0237_;
  assign _0242_ = rd_ptr_bin[0] ? \mem[9] [29] : \mem[8] [29];
  assign _0243_ = rd_ptr_bin[0] ? \mem[11] [29] : \mem[10] [29];
  assign _0244_ = rd_ptr_bin[1] ? _0243_ : _0242_;
  assign _0245_ = rd_ptr_bin[0] ? \mem[13] [29] : \mem[12] [29];
  assign _0246_ = rd_ptr_bin[0] ? \mem[15] [29] : \mem[14] [29];
  assign _0247_ = rd_ptr_bin[1] ? _0246_ : _0245_;
  assign _0248_ = rd_ptr_bin[2] ? _0247_ : _0244_;
  assign _0006_[29] = rd_ptr_bin[3] ? _0248_ : _0241_;
  assign _0249_ = rd_ptr_bin[0] ? \mem[1] [30] : \mem[0] [30];
  assign _0250_ = rd_ptr_bin[0] ? \mem[3] [30] : \mem[2] [30];
  assign _0251_ = rd_ptr_bin[1] ? _0250_ : _0249_;
  assign _0252_ = rd_ptr_bin[0] ? \mem[5] [30] : \mem[4] [30];
  assign _0253_ = rd_ptr_bin[0] ? \mem[7] [30] : \mem[6] [30];
  assign _0254_ = rd_ptr_bin[1] ? _0253_ : _0252_;
  assign _0255_ = rd_ptr_bin[2] ? _0254_ : _0251_;
  assign _0256_ = rd_ptr_bin[0] ? \mem[9] [30] : \mem[8] [30];
  assign _0257_ = rd_ptr_bin[0] ? \mem[11] [30] : \mem[10] [30];
  assign _0258_ = rd_ptr_bin[1] ? _0257_ : _0256_;
  assign _0259_ = rd_ptr_bin[0] ? \mem[13] [30] : \mem[12] [30];
  assign _0260_ = rd_ptr_bin[0] ? \mem[15] [30] : \mem[14] [30];
  assign _0261_ = rd_ptr_bin[1] ? _0260_ : _0259_;
  assign _0262_ = rd_ptr_bin[2] ? _0261_ : _0258_;
  assign _0006_[30] = rd_ptr_bin[3] ? _0262_ : _0255_;
  assign _0263_ = rd_ptr_bin[0] ? \mem[1] [31] : \mem[0] [31];
  assign _0264_ = rd_ptr_bin[0] ? \mem[3] [31] : \mem[2] [31];
  assign _0265_ = rd_ptr_bin[1] ? _0264_ : _0263_;
  assign _0266_ = rd_ptr_bin[0] ? \mem[5] [31] : \mem[4] [31];
  assign _0267_ = rd_ptr_bin[0] ? \mem[7] [31] : \mem[6] [31];
  assign _0268_ = rd_ptr_bin[1] ? _0267_ : _0266_;
  assign _0269_ = rd_ptr_bin[2] ? _0268_ : _0265_;
  assign _0270_ = rd_ptr_bin[0] ? \mem[9] [31] : \mem[8] [31];
  assign _0271_ = rd_ptr_bin[0] ? \mem[11] [31] : \mem[10] [31];
  assign _0272_ = rd_ptr_bin[1] ? _0271_ : _0270_;
  assign _0273_ = rd_ptr_bin[0] ? \mem[13] [31] : \mem[12] [31];
  assign _0274_ = rd_ptr_bin[0] ? \mem[15] [31] : \mem[14] [31];
  assign _0275_ = rd_ptr_bin[1] ? _0274_ : _0273_;
  assign _0276_ = rd_ptr_bin[2] ? _0275_ : _0272_;
  assign _0006_[31] = rd_ptr_bin[3] ? _0276_ : _0269_;
  assign rd_ptr_bin_next[4] = ~_0392_;
  assign _0626_[1] = ~_0359_;
  assign _0277_ = wr_ptr_bin[1] | wr_ptr_bin[0];
  assign _0278_ = wr_ptr_bin[3] | wr_ptr_bin[2];
  assign _0279_ = _0278_ | _0277_;
  assign _0007_ = do_write & ~(_0279_);
  assign _0280_ = _0278_ | _0418_;
  assign _0014_ = do_write & ~(_0280_);
  assign wr_ptr_bin_next[4] = ~_0411_;
  assign \bin2gray$func$../rtl/fifo_async.v:236$19.$result [3] = ~_0415_;
  assign \bin2gray$func$../rtl/fifo_async.v:236$19.$result [0] = ~_0421_;
  assign \bin2gray$func$../rtl/fifo_async.v:236$19.$result [1] = ~_0424_;
  assign \bin2gray$func$../rtl/fifo_async.v:236$19.$result [2] = ~_0427_;
  assign wr_ptr_bin_next[1] = ~_0420_;
  assign wr_ptr_bin_next[3] = ~_0414_;
  assign _0281_ = _0278_ | _0419_;
  assign _0015_ = do_write & ~(_0281_);
  assign _0282_ = _0278_ | ~(_0409_);
  assign _0016_ = do_write & ~(_0282_);
  assign _0283_ = wr_ptr_bin[3] | ~(wr_ptr_bin[2]);
  assign _0284_ = _0283_ | _0277_;
  assign _0017_ = do_write & ~(_0284_);
  assign _0285_ = _0283_ | _0418_;
  assign _0018_ = do_write & ~(_0285_);
  assign _0286_ = _0283_ | _0419_;
  assign _0019_ = do_write & ~(_0286_);
  assign _0287_ = _0283_ | ~(_0409_);
  assign _0020_ = do_write & ~(_0287_);
  assign _0288_ = wr_ptr_bin[2] | ~(wr_ptr_bin[3]);
  assign _0289_ = _0288_ | _0277_;
  assign _0021_ = do_write & ~(_0289_);
  assign rd_ptr_bin_next[3] = ~_0385_;
  assign _0290_ = _0288_ | _0418_;
  assign _0022_ = do_write & ~(_0290_);
  assign _0291_ = _0288_ | _0419_;
  assign _0008_ = do_write & ~(_0291_);
  assign _0292_ = _0288_ | ~(_0409_);
  assign _0009_ = do_write & ~(_0292_);
  assign _0293_ = _0277_ | ~(_0408_);
  assign _0010_ = do_write & ~(_0293_);
  assign _0294_ = _0418_ | ~(_0408_);
  assign _0011_ = do_write & ~(_0294_);
  assign _0295_ = _0419_ | ~(_0408_);
  assign _0012_ = do_write & ~(_0295_);
  assign _0013_ = _0410_ & do_write;
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0012_) \mem[14] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0009_) \mem[11] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0011_) \mem[13] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0008_) \mem[10] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0007_) \mem[0] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0021_) \mem[8] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0020_) \mem[7] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0013_) \mem[15] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0019_) \mem[6] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0018_) \mem[5] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0017_) \mem[4] [31] <= wr_data[31];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_ptr_gray[0] <= 1'h0;
    else if (do_write) wr_ptr_gray[0] <= \bin2gray$func$../rtl/fifo_async.v:236$19.$result [0];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_ptr_gray[1] <= 1'h0;
    else if (do_write) wr_ptr_gray[1] <= \bin2gray$func$../rtl/fifo_async.v:236$19.$result [1];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_ptr_gray[2] <= 1'h0;
    else if (do_write) wr_ptr_gray[2] <= \bin2gray$func$../rtl/fifo_async.v:236$19.$result [2];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_ptr_gray[3] <= 1'h0;
    else if (do_write) wr_ptr_gray[3] <= \bin2gray$func$../rtl/fifo_async.v:236$19.$result [3];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_ptr_gray[4] <= 1'h0;
    else if (do_write) wr_ptr_gray[4] <= wr_ptr_bin_next[4];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_ptr_gray[0] <= 1'h0;
    else if (do_read) rd_ptr_gray[0] <= \bin2gray$func$../rtl/fifo_async.v:267$20.$result [0];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_ptr_gray[1] <= 1'h0;
    else if (do_read) rd_ptr_gray[1] <= \bin2gray$func$../rtl/fifo_async.v:267$20.$result [1];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_ptr_gray[2] <= 1'h0;
    else if (do_read) rd_ptr_gray[2] <= \bin2gray$func$../rtl/fifo_async.v:267$20.$result [2];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_ptr_gray[3] <= 1'h0;
    else if (do_read) rd_ptr_gray[3] <= \bin2gray$func$../rtl/fifo_async.v:267$20.$result [3];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_ptr_gray[4] <= 1'h0;
    else if (do_read) rd_ptr_gray[4] <= rd_ptr_bin_next[4];
  reg \wr_ptr_bin_reg[0] ;
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) \wr_ptr_bin_reg[0]  <= 1'h0;
    else if (do_write) \wr_ptr_bin_reg[0]  <= wr_ptr_bin_next[0];
  assign wr_ptr_bin[0] = \wr_ptr_bin_reg[0] ;
  reg \wr_ptr_bin_reg[1] ;
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) \wr_ptr_bin_reg[1]  <= 1'h0;
    else if (do_write) \wr_ptr_bin_reg[1]  <= wr_ptr_bin_next[1];
  assign wr_ptr_bin[1] = \wr_ptr_bin_reg[1] ;
  reg \wr_ptr_bin_reg[2] ;
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) \wr_ptr_bin_reg[2]  <= 1'h0;
    else if (do_write) \wr_ptr_bin_reg[2]  <= wr_ptr_bin_next[2];
  assign wr_ptr_bin[2] = \wr_ptr_bin_reg[2] ;
  reg \wr_ptr_bin_reg[3] ;
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) \wr_ptr_bin_reg[3]  <= 1'h0;
    else if (do_write) \wr_ptr_bin_reg[3]  <= wr_ptr_bin_next[3];
  assign wr_ptr_bin[3] = \wr_ptr_bin_reg[3] ;
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0022_) \mem[9] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0016_) \mem[3] [31] <= wr_data[31];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0010_) \mem[12] [31] <= wr_data[31];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[0] <= 1'h0;
    else if (do_read) rd_data[0] <= _0006_[0];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[1] <= 1'h0;
    else if (do_read) rd_data[1] <= _0006_[1];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[2] <= 1'h0;
    else if (do_read) rd_data[2] <= _0006_[2];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[3] <= 1'h0;
    else if (do_read) rd_data[3] <= _0006_[3];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[4] <= 1'h0;
    else if (do_read) rd_data[4] <= _0006_[4];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[5] <= 1'h0;
    else if (do_read) rd_data[5] <= _0006_[5];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[6] <= 1'h0;
    else if (do_read) rd_data[6] <= _0006_[6];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[7] <= 1'h0;
    else if (do_read) rd_data[7] <= _0006_[7];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[8] <= 1'h0;
    else if (do_read) rd_data[8] <= _0006_[8];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[9] <= 1'h0;
    else if (do_read) rd_data[9] <= _0006_[9];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[10] <= 1'h0;
    else if (do_read) rd_data[10] <= _0006_[10];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[11] <= 1'h0;
    else if (do_read) rd_data[11] <= _0006_[11];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[12] <= 1'h0;
    else if (do_read) rd_data[12] <= _0006_[12];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[13] <= 1'h0;
    else if (do_read) rd_data[13] <= _0006_[13];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[14] <= 1'h0;
    else if (do_read) rd_data[14] <= _0006_[14];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[15] <= 1'h0;
    else if (do_read) rd_data[15] <= _0006_[15];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[16] <= 1'h0;
    else if (do_read) rd_data[16] <= _0006_[16];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[17] <= 1'h0;
    else if (do_read) rd_data[17] <= _0006_[17];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[18] <= 1'h0;
    else if (do_read) rd_data[18] <= _0006_[18];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[19] <= 1'h0;
    else if (do_read) rd_data[19] <= _0006_[19];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[20] <= 1'h0;
    else if (do_read) rd_data[20] <= _0006_[20];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[21] <= 1'h0;
    else if (do_read) rd_data[21] <= _0006_[21];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[22] <= 1'h0;
    else if (do_read) rd_data[22] <= _0006_[22];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[23] <= 1'h0;
    else if (do_read) rd_data[23] <= _0006_[23];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[24] <= 1'h0;
    else if (do_read) rd_data[24] <= _0006_[24];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[25] <= 1'h0;
    else if (do_read) rd_data[25] <= _0006_[25];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[26] <= 1'h0;
    else if (do_read) rd_data[26] <= _0006_[26];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[27] <= 1'h0;
    else if (do_read) rd_data[27] <= _0006_[27];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[28] <= 1'h0;
    else if (do_read) rd_data[28] <= _0006_[28];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[29] <= 1'h0;
    else if (do_read) rd_data[29] <= _0006_[29];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[30] <= 1'h0;
    else if (do_read) rd_data[30] <= _0006_[30];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data[31] <= 1'h0;
    else if (do_read) rd_data[31] <= _0006_[31];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0015_) \mem[2] [31] <= wr_data[31];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) overflow <= 1'h0;
    else overflow <= _0004_;
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) underflow <= 1'h0;
    else underflow <= _0005_;
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [0] <= wr_data[0];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [1] <= wr_data[1];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [2] <= wr_data[2];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [3] <= wr_data[3];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [4] <= wr_data[4];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [5] <= wr_data[5];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [6] <= wr_data[6];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [7] <= wr_data[7];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [8] <= wr_data[8];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [9] <= wr_data[9];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [10] <= wr_data[10];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [11] <= wr_data[11];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [12] <= wr_data[12];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [13] <= wr_data[13];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [14] <= wr_data[14];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [15] <= wr_data[15];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [16] <= wr_data[16];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [17] <= wr_data[17];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [18] <= wr_data[18];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [19] <= wr_data[19];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [20] <= wr_data[20];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [21] <= wr_data[21];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [22] <= wr_data[22];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [23] <= wr_data[23];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [24] <= wr_data[24];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [25] <= wr_data[25];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [26] <= wr_data[26];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [27] <= wr_data[27];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [28] <= wr_data[28];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [29] <= wr_data[29];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [30] <= wr_data[30];
  always @(posedge wr_clk)
    if (_0014_) \mem[1] [31] <= wr_data[31];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) almost_empty <= 1'h1;
    else almost_empty <= _0000_;
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) full <= 1'h0;
    else full <= _0003_;
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) empty <= 1'h1;
    else empty <= _0002_;
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_data_count[0] <= 1'h0;
    else wr_data_count[0] <= _0626_[0];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_data_count[1] <= 1'h0;
    else wr_data_count[1] <= _0626_[1];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_data_count[2] <= 1'h0;
    else wr_data_count[2] <= _0626_[2];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_data_count[3] <= 1'h0;
    else wr_data_count[3] <= _0626_[3];
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) wr_data_count[4] <= 1'h0;
    else wr_data_count[4] <= _0626_[4];
  reg \rd_ptr_bin_reg[0] ;
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) \rd_ptr_bin_reg[0]  <= 1'h0;
    else if (do_read) \rd_ptr_bin_reg[0]  <= rd_ptr_bin_next[0];
  assign rd_ptr_bin[0] = \rd_ptr_bin_reg[0] ;
  reg \rd_ptr_bin_reg[1] ;
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) \rd_ptr_bin_reg[1]  <= 1'h0;
    else if (do_read) \rd_ptr_bin_reg[1]  <= rd_ptr_bin_next[1];
  assign rd_ptr_bin[1] = \rd_ptr_bin_reg[1] ;
  reg \rd_ptr_bin_reg[2] ;
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) \rd_ptr_bin_reg[2]  <= 1'h0;
    else if (do_read) \rd_ptr_bin_reg[2]  <= rd_ptr_bin_next[2];
  assign rd_ptr_bin[2] = \rd_ptr_bin_reg[2] ;
  reg \rd_ptr_bin_reg[3] ;
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) \rd_ptr_bin_reg[3]  <= 1'h0;
    else if (do_read) \rd_ptr_bin_reg[3]  <= rd_ptr_bin_next[3];
  assign rd_ptr_bin[3] = \rd_ptr_bin_reg[3] ;
  always @(posedge wr_clk, negedge wr_rst_n)
    if (!wr_rst_n) almost_full <= 1'h0;
    else almost_full <= _0001_;
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data_count[0] <= 1'h0;
    else rd_data_count[0] <= _0625_[0];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data_count[1] <= 1'h0;
    else rd_data_count[1] <= _0625_[1];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data_count[2] <= 1'h0;
    else rd_data_count[2] <= _0625_[2];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data_count[3] <= 1'h0;
    else rd_data_count[3] <= _0625_[3];
  always @(posedge rd_clk, negedge rd_rst_n)
    if (!rd_rst_n) rd_data_count[4] <= 1'h0;
    else rd_data_count[4] <= _0625_[4];
  \$paramod$2d1f5da734bda88c85121ae0bcafa174ce0747b6\synchronizer  sync_rd_ptr (
    .async_in(rd_ptr_gray),
    .clk(wr_clk),
    .rst_n(wr_rst_n),
    .sync_out(rd_ptr_gray_sync)
  );
  \$paramod$2d1f5da734bda88c85121ae0bcafa174ce0747b6\synchronizer  sync_wr_ptr (
    .async_in(wr_ptr_gray),
    .clk(rd_clk),
    .rst_n(rd_rst_n),
    .sync_out(wr_ptr_gray_sync)
  );
  assign _0625_[30:5] = { _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31], _0625_[31] };
  assign _0626_[30:5] = { _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31], _0626_[31] };
  assign \bin2gray$func$../rtl/fifo_async.v:236$19.$result [4] = wr_ptr_bin_next[4];
  assign \bin2gray$func$../rtl/fifo_async.v:236$23.binary  = 5'hxx;
  assign \bin2gray$func$../rtl/fifo_async.v:267$20.$result [4] = rd_ptr_bin_next[4];
  assign \bin2gray$func$../rtl/fifo_async.v:267$24.binary  = 5'hxx;
  assign \gray2bin$func$../rtl/fifo_async.v:321$25.gray  = 5'hxx;
  assign \gray2bin$func$../rtl/fifo_async.v:321$25.i  = 32'hxxxxxxxx;
  assign \gray2bin$func$../rtl/fifo_async.v:322$26.gray  = 5'hxx;
  assign \gray2bin$func$../rtl/fifo_async.v:322$26.i  = 32'hxxxxxxxx;
  assign rd_addr = rd_ptr_bin[3:0];
  assign rd_ptr_bin[4] = rd_ptr_gray[4];
  assign rd_ptr_bin_sync[4] = rd_ptr_gray_sync[4];
  assign rd_ptr_gray_next = { rd_ptr_bin_next[4], \bin2gray$func$../rtl/fifo_async.v:267$20.$result [3:0] };
  assign wr_addr = wr_ptr_bin[3:0];
  assign wr_ptr_bin[4] = wr_ptr_gray[4];
  assign wr_ptr_bin_sync[4] = wr_ptr_gray_sync[4];
  assign wr_ptr_gray_next = { wr_ptr_bin_next[4], \bin2gray$func$../rtl/fifo_async.v:236$19.$result [3:0] };
endmodule
